// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AgreementType.
const (
	AgreementTypeApprovedResearcher AgreementType = "approved-researcher"
	AgreementTypeStudyOwner         AgreementType = "study-owner"
)

// Defines values for ApprovalStatus.
const (
	Approved   ApprovalStatus = "Approved"
	Incomplete ApprovalStatus = "Incomplete"
	Pending    ApprovalStatus = "Pending"
	Rejected   ApprovalStatus = "Rejected"
)

// Defines values for AssetClassificationImpact.
const (
	AssetClassificationImpactConfidential       AssetClassificationImpact = "confidential"
	AssetClassificationImpactHighlyConfidential AssetClassificationImpact = "highly_confidential"
	AssetClassificationImpactPublic             AssetClassificationImpact = "public"
)

// Defines values for AssetFormat.
const (
	AssetFormatElectronic AssetFormat = "electronic"
	AssetFormatOther      AssetFormat = "other"
	AssetFormatPaper      AssetFormat = "paper"
)

// Defines values for AssetLegalBasis.
const (
	AssetLegalBasisConsent             AssetLegalBasis = "consent"
	AssetLegalBasisContract            AssetLegalBasis = "contract"
	AssetLegalBasisLegalObligation     AssetLegalBasis = "legal_obligation"
	AssetLegalBasisLegitimateInterests AssetLegalBasis = "legitimate_interests"
	AssetLegalBasisPublicTask          AssetLegalBasis = "public_task"
	AssetLegalBasisVitalInterests      AssetLegalBasis = "vital_interests"
)

// Defines values for AssetProtection.
const (
	AssetProtectionAnonymisation                             AssetProtection = "anonymisation"
	AssetProtectionIdentifiableLowConfidencePseudonymisation AssetProtection = "identifiable_low_confidence_pseudonymisation"
	AssetProtectionPseudonymisation                          AssetProtection = "pseudonymisation"
)

// Defines values for AssetStatus.
const (
	AssetStatusActive    AssetStatus = "active"
	AssetStatusAwaiting  AssetStatus = "awaiting"
	AssetStatusDestroyed AssetStatus = "destroyed"
)

// Defines values for AssetBaseClassificationImpact.
const (
	AssetBaseClassificationImpactConfidential       AssetBaseClassificationImpact = "confidential"
	AssetBaseClassificationImpactHighlyConfidential AssetBaseClassificationImpact = "highly_confidential"
	AssetBaseClassificationImpactPublic             AssetBaseClassificationImpact = "public"
)

// Defines values for AssetBaseFormat.
const (
	AssetBaseFormatElectronic AssetBaseFormat = "electronic"
	AssetBaseFormatOther      AssetBaseFormat = "other"
	AssetBaseFormatPaper      AssetBaseFormat = "paper"
)

// Defines values for AssetBaseLegalBasis.
const (
	AssetBaseLegalBasisConsent             AssetBaseLegalBasis = "consent"
	AssetBaseLegalBasisContract            AssetBaseLegalBasis = "contract"
	AssetBaseLegalBasisLegalObligation     AssetBaseLegalBasis = "legal_obligation"
	AssetBaseLegalBasisLegitimateInterests AssetBaseLegalBasis = "legitimate_interests"
	AssetBaseLegalBasisPublicTask          AssetBaseLegalBasis = "public_task"
	AssetBaseLegalBasisVitalInterests      AssetBaseLegalBasis = "vital_interests"
)

// Defines values for AssetBaseProtection.
const (
	AssetBaseProtectionAnonymisation                             AssetBaseProtection = "anonymisation"
	AssetBaseProtectionIdentifiableLowConfidencePseudonymisation AssetBaseProtection = "identifiable_low_confidence_pseudonymisation"
	AssetBaseProtectionPseudonymisation                          AssetBaseProtection = "pseudonymisation"
)

// Defines values for AssetBaseStatus.
const (
	AssetBaseStatusActive    AssetBaseStatus = "active"
	AssetBaseStatusAwaiting  AssetBaseStatus = "awaiting"
	AssetBaseStatusDestroyed AssetBaseStatus = "destroyed"
)

// Defines values for AuthRoles.
const (
	AuthRolesAdmin                         AuthRoles = "admin"
	AuthRolesApprovedResearcher            AuthRoles = "approved-researcher"
	AuthRolesApprovedStaffResearcher       AuthRoles = "approved-staff-researcher"
	AuthRolesBase                          AuthRoles = "base"
	AuthRolesIgOpsStaff                    AuthRoles = "ig-ops-staff"
	AuthRolesInformationAssetAdministrator AuthRoles = "information-asset-administrator"
	AuthRolesInformationAssetOwner         AuthRoles = "information-asset-owner"
	AuthRolesStaff                         AuthRoles = "staff"
	AuthRolesTreOpsStaff                   AuthRoles = "tre-ops-staff"
)

// Defines values for ContractStatus.
const (
	ContractStatusActive   ContractStatus = "active"
	ContractStatusExpired  ContractStatus = "expired"
	ContractStatusProposed ContractStatus = "proposed"
)

// Defines values for ContractBaseStatus.
const (
	ContractBaseStatusActive   ContractBaseStatus = "active"
	ContractBaseStatusExpired  ContractBaseStatus = "expired"
	ContractBaseStatusProposed ContractBaseStatus = "proposed"
)

// Defines values for ContractUpdateStatus.
const (
	ContractUpdateStatusActive   ContractUpdateStatus = "active"
	ContractUpdateStatusExpired  ContractUpdateStatus = "expired"
	ContractUpdateStatusProposed ContractUpdateStatus = "proposed"
)

// Defines values for ContractUploadObjectStatus.
const (
	ContractUploadObjectStatusActive   ContractUploadObjectStatus = "active"
	ContractUploadObjectStatusExpired  ContractUploadObjectStatus = "expired"
	ContractUploadObjectStatusProposed ContractUploadObjectStatus = "proposed"
)

// Defines values for ProjectTRERoleName.
const (
	DesktopUser     ProjectTRERoleName = "desktop_user"
	EgressChecker   ProjectTRERoleName = "egress_checker"
	EgressRequester ProjectTRERoleName = "egress_requester"
	Egresser        ProjectTRERoleName = "egresser"
	Ingresser       ProjectTRERoleName = "ingresser"
	TrustedEgresser ProjectTRERoleName = "trusted_egresser"
)

// Defines values for TrainingKind.
const (
	TrainingKindNhsd TrainingKind = "training_kind_nhsd"
)

// Agreement defines model for Agreement.
type Agreement struct {
	// Id UUID of the agreement
	Id   string `json:"id"`
	Text string `json:"text"`
}

// AgreementConfirmation defines model for AgreementConfirmation.
type AgreementConfirmation struct {
	// AgreementId UUID of the agreement that has been agreed to
	AgreementId string `json:"agreement_id"`
}

// AgreementType defines model for AgreementType.
type AgreementType string

// ApprovalStatus Current approval status (used for studies, projects, etc.)
type ApprovalStatus string

// Asset defines model for Asset.
type Asset struct {
	// ClassificationImpact Classification level of the asset
	ClassificationImpact AssetClassificationImpact `json:"classification_impact"`

	// CreatedAt Time in RFC3339 format when the asset was created
	CreatedAt string `json:"created_at"`

	// CreatorUserId Unique identifier of the user who created the asset
	CreatorUserId string `json:"creator_user_id"`

	// Description Description of the asset
	Description string `json:"description"`

	// ExpiresAt Retention expiry date of the asset
	ExpiresAt string `json:"expires_at"`

	// Format Format of the asset
	Format AssetFormat `json:"format"`

	// HasDspt Whether there is an up to date Data Security & Protection Toolkit in place
	HasDspt bool `json:"has_dspt"`

	// Id Unique identifier for the asset
	Id string `json:"id"`

	// LegalBasis Legal basis for holding the asset
	LegalBasis AssetLegalBasis `json:"legal_basis"`

	// Locations Storage locations and touchpoints for the asset
	Locations []string `json:"locations"`

	// Protection Type of protection applied to the asset
	Protection AssetProtection `json:"protection"`

	// RequiresContract Whether a contract is required for the asset
	RequiresContract bool `json:"requires_contract"`

	// Status Status of the asset
	Status AssetStatus `json:"status"`

	// StoredOutsideUkEea Whether the asset is stored or processed outside UK and EEA
	StoredOutsideUkEea bool `json:"stored_outside_uk_eea"`

	// StudyId Unique identifier of the study to which the asset belongs
	StudyId string `json:"study_id"`

	// Tier Security tier level for the asset (0=public, 1=confidential, 2-4=highly confidential)
	Tier int `json:"tier"`

	// Title Title of the asset
	Title string `json:"title"`

	// UpdatedAt Time in RFC3339 format when the asset was last updated
	UpdatedAt string `json:"updated_at"`
}

// AssetClassificationImpact Classification level of the asset
type AssetClassificationImpact string

// AssetFormat Format of the asset
type AssetFormat string

// AssetLegalBasis Legal basis for holding the asset
type AssetLegalBasis string

// AssetProtection Type of protection applied to the asset
type AssetProtection string

// AssetStatus Status of the asset
type AssetStatus string

// AssetBase A data asset representing a set of related data entities
type AssetBase struct {
	// ClassificationImpact Classification level of the asset
	ClassificationImpact AssetBaseClassificationImpact `json:"classification_impact"`

	// Description Description of the asset
	Description string `json:"description"`

	// ExpiresAt Retention expiry date of the asset
	ExpiresAt string `json:"expires_at"`

	// Format Format of the asset
	Format AssetBaseFormat `json:"format"`

	// HasDspt Whether there is an up to date Data Security & Protection Toolkit in place
	HasDspt bool `json:"has_dspt"`

	// LegalBasis Legal basis for holding the asset
	LegalBasis AssetBaseLegalBasis `json:"legal_basis"`

	// Locations Storage locations and touchpoints for the asset
	Locations []string `json:"locations"`

	// Protection Type of protection applied to the asset
	Protection AssetBaseProtection `json:"protection"`

	// RequiresContract Whether a contract is required for the asset
	RequiresContract bool `json:"requires_contract"`

	// Status Status of the asset
	Status AssetBaseStatus `json:"status"`

	// StoredOutsideUkEea Whether the asset is stored or processed outside UK and EEA
	StoredOutsideUkEea bool `json:"stored_outside_uk_eea"`

	// Tier Security tier level for the asset (0=public, 1=confidential, 2-4=highly confidential)
	Tier int `json:"tier"`

	// Title Title of the asset
	Title string `json:"title"`
}

// AssetBaseClassificationImpact Classification level of the asset
type AssetBaseClassificationImpact string

// AssetBaseFormat Format of the asset
type AssetBaseFormat string

// AssetBaseLegalBasis Legal basis for holding the asset
type AssetBaseLegalBasis string

// AssetBaseProtection Type of protection applied to the asset
type AssetBaseProtection string

// AssetBaseStatus Status of the asset
type AssetBaseStatus string

// Auth defines model for Auth.
type Auth struct {
	// Roles List of roles assigned to the user. This array can contain both:
	// - Global roles (see below enum values): System-wide roles like admin, staff, approved-researcher
	// - Additional dynamic resource-specific roles: Runtime roles like project_{id}_owner, study_{id}_admin
	Roles    []AuthRoles `json:"roles"`
	Username string      `json:"username"`
}

// AuthRoles defines model for Auth.Roles.
type AuthRoles string

// ConfirmedAgreement defines model for ConfirmedAgreement.
type ConfirmedAgreement struct {
	AgreementType AgreementType `json:"agreement_type"`

	// ConfirmedAt Time in RFC3339 format at which the agreement was confirmed
	ConfirmedAt string `json:"confirmed_at"`
}

// Contract defines model for Contract.
type Contract struct {
	// Assets List of assets associated with this contract
	Assets *[]Asset `json:"assets,omitempty"`

	// CreatedAt Time in RFC3339 format when the contract was created
	CreatedAt string `json:"created_at"`

	// ExpiryDate Contract expiry date in YYYY-MM-DD format
	ExpiryDate string `json:"expiry_date"`

	// Filename Original filename of the uploaded contract
	Filename string `json:"filename"`

	// Id Unique identifier for the contract
	Id string `json:"id"`

	// OrganisationSignatory Name of the organisation signatory
	OrganisationSignatory string `json:"organisation_signatory"`

	// StartDate Contract start date in YYYY-MM-DD format
	StartDate string `json:"start_date"`

	// Status Current status of the contract
	Status ContractStatus `json:"status"`

	// StudyId Unique identifier of the study to which the contract belongs
	StudyId string `json:"study_id"`

	// ThirdPartyName Name of the third party organization
	ThirdPartyName string `json:"third_party_name"`

	// UpdatedAt Time in RFC3339 format when the contract was last updated
	UpdatedAt string `json:"updated_at"`
}

// ContractStatus Current status of the contract
type ContractStatus string

// ContractBase defines model for ContractBase.
type ContractBase struct {
	// Assets List of assets associated with this contract
	Assets *[]Asset `json:"assets,omitempty"`

	// ExpiryDate Contract expiry date in YYYY-MM-DD format
	ExpiryDate string `json:"expiry_date"`

	// OrganisationSignatory Name of the organisation signatory
	OrganisationSignatory string `json:"organisation_signatory"`

	// StartDate Contract start date in YYYY-MM-DD format
	StartDate string `json:"start_date"`

	// Status Current status of the contract
	Status ContractBaseStatus `json:"status"`

	// ThirdPartyName Name of the third party organization
	ThirdPartyName string `json:"third_party_name"`
}

// ContractBaseStatus Current status of the contract
type ContractBaseStatus string

// ContractUpdate defines model for ContractUpdate.
type ContractUpdate struct {
	// Assets List of assets associated with this contract
	Assets *[]Asset `json:"assets,omitempty"`

	// ExpiryDate Contract expiry date in YYYY-MM-DD format
	ExpiryDate string `json:"expiry_date"`

	// File Optional new contract file to replace the existing one
	File *openapi_types.File `json:"file,omitempty"`

	// OrganisationSignatory Name of the organisation signatory
	OrganisationSignatory string `json:"organisation_signatory"`

	// StartDate Contract start date in YYYY-MM-DD format
	StartDate string `json:"start_date"`

	// Status Current status of the contract
	Status ContractUpdateStatus `json:"status"`

	// ThirdPartyName Name of the third party organization
	ThirdPartyName string `json:"third_party_name"`
}

// ContractUpdateStatus Current status of the contract
type ContractUpdateStatus string

// ContractUploadObject defines model for ContractUploadObject.
type ContractUploadObject struct {
	// Assets List of assets associated with this contract
	Assets *[]Asset `json:"assets,omitempty"`

	// ExpiryDate Contract expiry date in YYYY-MM-DD format
	ExpiryDate string `json:"expiry_date"`

	// File The contract file to upload (e.g., PDF)
	File openapi_types.File `json:"file"`

	// OrganisationSignatory Name of the organisation signatory
	OrganisationSignatory string `json:"organisation_signatory"`

	// StartDate Contract start date in YYYY-MM-DD format
	StartDate string `json:"start_date"`

	// Status Current status of the contract
	Status ContractUploadObjectStatus `json:"status"`

	// ThirdPartyName Name of the third party organization
	ThirdPartyName string `json:"third_party_name"`
}

// ContractUploadObjectStatus Current status of the contract
type ContractUploadObjectStatus string

// Environment An environment with its tier mapping
type Environment struct {
	// Id Unique identifier for the environment
	Id string `json:"id"`

	// Name Name of the environment (e.g., "ARC Trusted Research Environment")
	Name string `json:"name"`

	// Tier Maximum data tier this environment can handle (assets with tier <= this value can be used)
	Tier int `json:"tier"`
}

// Profile defines model for Profile.
type Profile struct {
	ChosenName string `json:"chosen_name"`
	Username   string `json:"username"`
}

// ProfileTraining defines model for ProfileTraining.
type ProfileTraining struct {
	// TrainingRecords List of all training records for the user
	TrainingRecords []TrainingRecord `json:"training_records"`
}

// ProfileTrainingResponse defines model for ProfileTrainingResponse.
type ProfileTrainingResponse struct {
	// CertificateIsValid Is the certificate valid
	CertificateIsValid *bool `json:"certificate_is_valid,omitempty"`

	// CertificateIssuedAt Time in RFC3339 format at which the the certificate was issued
	CertificateIssuedAt *string `json:"certificate_issued_at,omitempty"`

	// CertificateMessage Reason why the training certificate is valid/invalid
	CertificateMessage *string `json:"certificate_message,omitempty"`
}

// ProfileTrainingUpdate defines model for ProfileTrainingUpdate.
type ProfileTrainingUpdate struct {
	// CertificateContentPdfBase64 Base64 encoded PDF file data of the certificate
	CertificateContentPdfBase64 *string      `json:"certificate_content_pdf_base64,omitempty"`
	Kind                        TrainingKind `json:"kind"`
}

// ProfileUpdate defines model for ProfileUpdate.
type ProfileUpdate struct {
	ChosenName string `json:"chosen_name"`
}

// Project A project with base details (environment-agnostic)
type Project struct {
	// ApprovalStatus Current approval status (used for studies, projects, etc.)
	ApprovalStatus ApprovalStatus `json:"approval_status"`

	// CreatedAt Time in RFC3339 format when the project was created
	CreatedAt string `json:"created_at"`

	// CreatorUsername Username of the user who created the project
	CreatorUsername string `json:"creator_username"`

	// EnvironmentName Name of the environment this project belongs to (e.g., "ARC Trusted Research Environment")
	EnvironmentName string `json:"environment_name"`

	// Id Unique identifier for the project
	Id string `json:"id"`

	// Name Name of the project
	Name string `json:"name"`

	// StudyId Unique identifier of the study to which the project belongs
	StudyId string `json:"study_id"`

	// UpdatedAt Time in RFC3339 format when the project was last updated
	UpdatedAt string `json:"updated_at"`
}

// ProjectTRE A TRE project with base project details and environment-specific data
type ProjectTRE struct {
	// ApprovalStatus Current approval status (used for studies, projects, etc.)
	ApprovalStatus ApprovalStatus `json:"approval_status"`

	// Assets List of assets associated with this project
	Assets []Asset `json:"assets"`

	// CreatedAt Time in RFC3339 format when the project was created
	CreatedAt string `json:"created_at"`

	// CreatorUsername Username of the user who created the project
	CreatorUsername string `json:"creator_username"`

	// EnvironmentName Name of the environment this project belongs to (e.g., "ARC Trusted Research Environment")
	EnvironmentName string `json:"environment_name"`

	// Id Unique identifier for the base project
	Id string `json:"id"`

	// Members List of project members with their roles (TRE-specific)
	Members []ProjectTREMember `json:"members"`

	// Name Name of the project
	Name string `json:"name"`

	// StudyId Unique identifier of the study to which the project belongs
	StudyId string `json:"study_id"`

	// StudyTitle Title of the study to which the project belongs
	StudyTitle string `json:"study_title"`

	// UpdatedAt Time in RFC3339 format when the project was last updated
	UpdatedAt string `json:"updated_at"`
}

// ProjectTREMember A project member with their assigned roles
type ProjectTREMember struct {
	// Roles List of roles to assign to this user (e.g., ["desktop_user", "ingresser"])
	Roles    []ProjectTRERoleName `json:"roles"`
	Username string               `json:"username"`
}

// ProjectTRERequest Request payload for creating a new TRE project
type ProjectTRERequest struct {
	// AssetIds List of asset identifiers to link to this project (can be empty)
	AssetIds []string `json:"asset_ids"`

	// Members List of project members with their roles (can be empty)
	Members []ProjectTREMember `json:"members"`

	// Name Name of the project
	Name string `json:"name"`

	// StudyId Unique identifier of the study to which the project belongs
	StudyId string `json:"study_id"`
}

// ProjectTRERoleName Available TRE project roles
type ProjectTRERoleName string

// ProjectTREUpdate Request payload for updating an existing TRE project (members and assets only)
type ProjectTREUpdate struct {
	// AssetIds List of asset identifiers to link to this project (can be empty)
	AssetIds []string `json:"asset_ids"`

	// Members List of project members with their roles (can be empty)
	Members []ProjectTREMember `json:"members"`
}

// Study defines model for Study.
type Study struct {
	// AdditionalStudyAdminUsernames List of additional study administrator usernames (empty array if none)
	AdditionalStudyAdminUsernames []string `json:"additional_study_admin_usernames"`

	// ApprovalStatus Current approval status (used for studies, projects, etc.)
	ApprovalStatus ApprovalStatus `json:"approval_status"`

	// CagReference CAG reference number
	CagReference *string `json:"cag_reference"`

	// CreatedAt Time in RFC3339 format when the study was created
	CreatedAt string `json:"created_at"`

	// DataControllerOrganisation The organisation acting as data controller for the study (e.g., "UCL" or custom organization name)
	DataControllerOrganisation string `json:"data_controller_organisation"`

	// DataProtectionNumber Full data protection registration number
	DataProtectionNumber *string `json:"data_protection_number"`

	// Description Description of the study
	Description *string `json:"description"`
	Feedback    *string `json:"feedback,omitempty"`

	// Id Unique identifier for the study
	Id string `json:"id"`

	// InvolvesCag Whether Confidentiality Advisory Group approval is involved (seeking/have sought)
	InvolvesCag *bool `json:"involves_cag"`

	// InvolvesDataProcessingOutsideEea Whether data is processed outside UK/EEA
	InvolvesDataProcessingOutsideEea *bool `json:"involves_data_processing_outside_eea"`

	// InvolvesEthicsApproval Whether Research Ethics Committee approval is involved (seeking/have sought)
	InvolvesEthicsApproval *bool `json:"involves_ethics_approval"`

	// InvolvesExternalUsers Whether external users will have access to the study
	InvolvesExternalUsers *bool `json:"involves_external_users"`

	// InvolvesHraApproval Whether Health Research Authority approval is involved (seeking/have sought)
	InvolvesHraApproval *bool `json:"involves_hra_approval"`

	// InvolvesIndirectDataCollection Whether data is collected indirectly for the study (e.g. via a third party)
	InvolvesIndirectDataCollection *bool `json:"involves_indirect_data_collection"`

	// InvolvesMnca Whether the HRA Model Non-Commercial Agreement is involved
	InvolvesMnca *bool `json:"involves_mnca"`

	// InvolvesNhsEngland Whether NHS England is involved in the research
	InvolvesNhsEngland *bool `json:"involves_nhs_england"`

	// InvolvesParticipantConsent Whether participant consent is involved (seeking/have sought)
	InvolvesParticipantConsent *bool `json:"involves_participant_consent"`

	// InvolvesThirdParty Whether third party organizations are involved
	InvolvesThirdParty *bool `json:"involves_third_party"`

	// InvolvesUclSponsorship Whether UCL sponsorship is involved (seeking/have sought)
	InvolvesUclSponsorship *bool `json:"involves_ucl_sponsorship"`

	// IrasId IRAS ID if applicable
	IrasId *string `json:"iras_id"`

	// IsDataProtectionOfficeRegistered Whether the study is registered with the UCL Data Protection Office
	IsDataProtectionOfficeRegistered *bool `json:"is_data_protection_office_registered"`

	// IsNhsAssociated Whether the research is associated with NHS
	IsNhsAssociated *bool `json:"is_nhs_associated"`

	// NhsEnglandReference NHS England DARS NIC number
	NhsEnglandReference *string `json:"nhs_england_reference"`

	// OwnerUserId ID of the user who owns the study
	OwnerUserId *string `json:"owner_user_id,omitempty"`

	// OwnerUsername Username of the user who owns the study
	OwnerUsername *string `json:"owner_username,omitempty"`

	// RequiresDbs Whether a DBS check is required for staff
	RequiresDbs *bool `json:"requires_dbs"`

	// RequiresDspt Whether NHS Data Security & Protection Toolkit is required
	RequiresDspt *bool `json:"requires_dspt"`

	// Title Title of the study
	Title string `json:"title"`

	// UpdatedAt Time in RFC3339 format when the study was last updated
	UpdatedAt string `json:"updated_at"`
}

// StudyAgreements defines model for StudyAgreements.
type StudyAgreements struct {
	// Usernames Usernames of those that have agreed to the study agreement
	Usernames []string `json:"usernames"`
}

// StudyBase Base study properties
type StudyBase struct {
	// AdditionalStudyAdminUsernames List of additional study administrator usernames (empty array if none)
	AdditionalStudyAdminUsernames []string `json:"additional_study_admin_usernames"`

	// CagReference CAG reference number
	CagReference *string `json:"cag_reference"`

	// DataControllerOrganisation The organisation acting as data controller for the study (e.g., "UCL" or custom organization name)
	DataControllerOrganisation string `json:"data_controller_organisation"`

	// DataProtectionNumber Full data protection registration number
	DataProtectionNumber *string `json:"data_protection_number"`

	// Description Description of the study
	Description *string `json:"description"`

	// InvolvesCag Whether Confidentiality Advisory Group approval is involved (seeking/have sought)
	InvolvesCag *bool `json:"involves_cag"`

	// InvolvesDataProcessingOutsideEea Whether data is processed outside UK/EEA
	InvolvesDataProcessingOutsideEea *bool `json:"involves_data_processing_outside_eea"`

	// InvolvesEthicsApproval Whether Research Ethics Committee approval is involved (seeking/have sought)
	InvolvesEthicsApproval *bool `json:"involves_ethics_approval"`

	// InvolvesExternalUsers Whether external users will have access to the study
	InvolvesExternalUsers *bool `json:"involves_external_users"`

	// InvolvesHraApproval Whether Health Research Authority approval is involved (seeking/have sought)
	InvolvesHraApproval *bool `json:"involves_hra_approval"`

	// InvolvesIndirectDataCollection Whether data is collected indirectly for the study (e.g. via a third party)
	InvolvesIndirectDataCollection *bool `json:"involves_indirect_data_collection"`

	// InvolvesMnca Whether the HRA Model Non-Commercial Agreement is involved
	InvolvesMnca *bool `json:"involves_mnca"`

	// InvolvesNhsEngland Whether NHS England is involved in the research
	InvolvesNhsEngland *bool `json:"involves_nhs_england"`

	// InvolvesParticipantConsent Whether participant consent is involved (seeking/have sought)
	InvolvesParticipantConsent *bool `json:"involves_participant_consent"`

	// InvolvesThirdParty Whether third party organizations are involved
	InvolvesThirdParty *bool `json:"involves_third_party"`

	// InvolvesUclSponsorship Whether UCL sponsorship is involved (seeking/have sought)
	InvolvesUclSponsorship *bool `json:"involves_ucl_sponsorship"`

	// IrasId IRAS ID if applicable
	IrasId *string `json:"iras_id"`

	// IsDataProtectionOfficeRegistered Whether the study is registered with the UCL Data Protection Office
	IsDataProtectionOfficeRegistered *bool `json:"is_data_protection_office_registered"`

	// IsNhsAssociated Whether the research is associated with NHS
	IsNhsAssociated *bool `json:"is_nhs_associated"`

	// NhsEnglandReference NHS England DARS NIC number
	NhsEnglandReference *string `json:"nhs_england_reference"`

	// OwnerUserId ID of the user who owns the study
	OwnerUserId *string `json:"owner_user_id,omitempty"`

	// OwnerUsername Username of the user who owns the study
	OwnerUsername *string `json:"owner_username,omitempty"`

	// RequiresDbs Whether a DBS check is required for staff
	RequiresDbs *bool `json:"requires_dbs"`

	// RequiresDspt Whether NHS Data Security & Protection Toolkit is required
	RequiresDspt *bool `json:"requires_dspt"`

	// Title Title of the study
	Title string `json:"title"`
}

// StudyRequest Base study properties
type StudyRequest = StudyBase

// StudyReview defines model for StudyReview.
type StudyReview struct {
	// Feedback Feedback for the study
	Feedback *string `json:"feedback,omitempty"`

	// Status Current approval status (used for studies, projects, etc.)
	Status ApprovalStatus `json:"status"`
}

// TrainingKind defines model for TrainingKind.
type TrainingKind string

// TrainingRecord defines model for TrainingRecord.
type TrainingRecord struct {
	// CompletedAt Time in RFC3339 format when the training was completed
	CompletedAt *string `json:"completed_at,omitempty"`

	// IsValid Whether this training certification is currently valid
	IsValid bool         `json:"is_valid"`
	Kind    TrainingKind `json:"kind"`
}

// User defines model for User.
type User struct {
	Id       string `json:"id"`
	Username string `json:"username"`
}

// UserAgreements defines model for UserAgreements.
type UserAgreements struct {
	ConfirmedAgreements []ConfirmedAgreement `json:"confirmed_agreements"`
}

// UserData defines model for UserData.
type UserData struct {
	Agreements     UserAgreements  `json:"agreements"`
	ChosenName     *string         `json:"chosen_name,omitempty"`
	Roles          []string        `json:"roles"`
	TrainingRecord ProfileTraining `json:"training_record"`
	User           User            `json:"user"`
}

// UserTrainingUpdate defines model for UserTrainingUpdate.
type UserTrainingUpdate struct {
	// TrainingDate Time in RFC3339 format at which the the certificate was issued
	TrainingDate string       `json:"training_date"`
	TrainingKind TrainingKind `json:"training_kind"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	// ErrorMessage Validation error message explaining why the request failed
	ErrorMessage string `json:"error_message"`
}

// GetStudiesParams defines parameters for GetStudies.
type GetStudiesParams struct {
	// Status get studies by status
	Status *ApprovalStatus `form:"status,omitempty" json:"status,omitempty"`
}

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {
	// Find user details to lookup by in entra. This can be valid within the user principal name, email, given name or display name eg. "tom", "hughes", "ccaeaea", "laura@example"
	Find string `form:"find" json:"find"`
}

// PostUsersInviteJSONBody defines parameters for PostUsersInvite.
type PostUsersInviteJSONBody struct {
	// Email Email address of the person to be invited
	Email string `json:"email"`
}

// PutUsersUserIdAttributesJSONBody defines parameters for PutUsersUserIdAttributes.
type PutUsersUserIdAttributesJSONBody struct {
	ChosenName string `json:"chosen_name"`
}

// PostProfileJSONRequestBody defines body for PostProfile for application/json ContentType.
type PostProfileJSONRequestBody = ProfileUpdate

// PostProfileAgreementsJSONRequestBody defines body for PostProfileAgreements for application/json ContentType.
type PostProfileAgreementsJSONRequestBody = AgreementConfirmation

// PostProfileTrainingJSONRequestBody defines body for PostProfileTraining for application/json ContentType.
type PostProfileTrainingJSONRequestBody = ProfileTrainingUpdate

// PostProjectsTreJSONRequestBody defines body for PostProjectsTre for application/json ContentType.
type PostProjectsTreJSONRequestBody = ProjectTRERequest

// PutProjectsTreProjectIdJSONRequestBody defines body for PutProjectsTreProjectId for application/json ContentType.
type PutProjectsTreProjectIdJSONRequestBody = ProjectTREUpdate

// PostStudiesJSONRequestBody defines body for PostStudies for application/json ContentType.
type PostStudiesJSONRequestBody = StudyRequest

// PostStudiesAdminStudyIdReviewJSONRequestBody defines body for PostStudiesAdminStudyIdReview for application/json ContentType.
type PostStudiesAdminStudyIdReviewJSONRequestBody = StudyReview

// PutStudiesStudyIdJSONRequestBody defines body for PutStudiesStudyId for application/json ContentType.
type PutStudiesStudyIdJSONRequestBody = StudyRequest

// PostStudiesStudyIdAgreementsJSONRequestBody defines body for PostStudiesStudyIdAgreements for application/json ContentType.
type PostStudiesStudyIdAgreementsJSONRequestBody = AgreementConfirmation

// PostStudiesStudyIdAssetsJSONRequestBody defines body for PostStudiesStudyIdAssets for application/json ContentType.
type PostStudiesStudyIdAssetsJSONRequestBody = AssetBase

// PostStudiesStudyIdContractsUploadMultipartRequestBody defines body for PostStudiesStudyIdContractsUpload for multipart/form-data ContentType.
type PostStudiesStudyIdContractsUploadMultipartRequestBody = ContractUploadObject

// PutStudiesStudyIdContractsContractIdMultipartRequestBody defines body for PutStudiesStudyIdContractsContractId for multipart/form-data ContentType.
type PutStudiesStudyIdContractsContractIdMultipartRequestBody = ContractUpdate

// PostUsersInviteJSONRequestBody defines body for PostUsersInvite for application/json ContentType.
type PostUsersInviteJSONRequestBody PostUsersInviteJSONBody

// PutUsersUserIdAttributesJSONRequestBody defines body for PutUsersUserIdAttributes for application/json ContentType.
type PutUsersUserIdAttributesJSONRequestBody PutUsersUserIdAttributesJSONBody

// PostUsersUserIdTrainingJSONRequestBody defines body for PostUsersUserIdTraining for application/json ContentType.
type PostUsersUserIdTrainingJSONRequestBody = UserTrainingUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /agreements/{agreementType})
	GetAgreementsAgreementType(c *gin.Context, agreementType AgreementType)

	// (GET /auth)
	GetAuth(c *gin.Context)

	// (GET /environments)
	GetEnvironments(c *gin.Context)

	// (GET /logout)
	GetLogout(c *gin.Context)

	// (GET /profile)
	GetProfile(c *gin.Context)

	// (POST /profile)
	PostProfile(c *gin.Context)

	// (GET /profile/agreements)
	GetProfileAgreements(c *gin.Context)

	// (POST /profile/agreements)
	PostProfileAgreements(c *gin.Context)

	// (GET /profile/training)
	GetProfileTraining(c *gin.Context)

	// (POST /profile/training)
	PostProfileTraining(c *gin.Context)

	// (GET /projects)
	GetProjects(c *gin.Context)

	// (GET /projects/tre)
	GetProjectsTre(c *gin.Context)

	// (POST /projects/tre)
	PostProjectsTre(c *gin.Context)

	// (POST /projects/tre/admin/{projectId}/approve)
	PostProjectsTreAdminProjectIdApprove(c *gin.Context, projectId string)

	// (GET /projects/tre/{projectId})
	GetProjectsTreProjectId(c *gin.Context, projectId string)

	// (PUT /projects/tre/{projectId})
	PutProjectsTreProjectId(c *gin.Context, projectId string)

	// (PATCH /projects/tre/{projectId}/pending)
	PatchProjectsTreProjectIdPending(c *gin.Context, projectId string)

	// (GET /studies)
	GetStudies(c *gin.Context, params GetStudiesParams)

	// (POST /studies)
	PostStudies(c *gin.Context)

	// (POST /studies/admin/{studyId}/review)
	PostStudiesAdminStudyIdReview(c *gin.Context, studyId string)

	// (GET /studies/{studyId})
	GetStudiesStudyId(c *gin.Context, studyId string)

	// (PUT /studies/{studyId})
	PutStudiesStudyId(c *gin.Context, studyId string)

	// (GET /studies/{studyId}/agreements)
	GetStudiesStudyIdAgreements(c *gin.Context, studyId string)

	// (POST /studies/{studyId}/agreements)
	PostStudiesStudyIdAgreements(c *gin.Context, studyId string)

	// (GET /studies/{studyId}/assets)
	GetStudiesStudyIdAssets(c *gin.Context, studyId string)

	// (POST /studies/{studyId}/assets)
	PostStudiesStudyIdAssets(c *gin.Context, studyId string)

	// (GET /studies/{studyId}/assets/{assetId})
	GetStudiesStudyIdAssetsAssetId(c *gin.Context, studyId string, assetId string)

	// (GET /studies/{studyId}/contracts)
	GetStudiesStudyIdContracts(c *gin.Context, studyId string)

	// (POST /studies/{studyId}/contracts/upload)
	PostStudiesStudyIdContractsUpload(c *gin.Context, studyId string)

	// (PUT /studies/{studyId}/contracts/{contractId})
	PutStudiesStudyIdContractsContractId(c *gin.Context, studyId string, contractId string)

	// (GET /studies/{studyId}/contracts/{contractId}/download)
	GetStudiesStudyIdContractsContractIdDownload(c *gin.Context, studyId string, contractId string)

	// (PATCH /studies/{studyId}/pending)
	PatchStudiesStudyIdPending(c *gin.Context, studyId string)

	// (GET /users)
	GetUsers(c *gin.Context, params GetUsersParams)

	// (POST /users/approved-researchers/import/csv)
	PostUsersApprovedResearchersImportCsv(c *gin.Context)

	// (POST /users/invite)
	PostUsersInvite(c *gin.Context)

	// (PUT /users/{userId}/attributes)
	PutUsersUserIdAttributes(c *gin.Context, userId string)

	// (POST /users/{userId}/training)
	PostUsersUserIdTraining(c *gin.Context, userId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAgreementsAgreementType operation middleware
func (siw *ServerInterfaceWrapper) GetAgreementsAgreementType(c *gin.Context) {

	var err error

	// ------------- Path parameter "agreementType" -------------
	var agreementType AgreementType

	err = runtime.BindStyledParameterWithOptions("simple", "agreementType", c.Param("agreementType"), &agreementType, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter agreementType: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAgreementsAgreementType(c, agreementType)
}

// GetAuth operation middleware
func (siw *ServerInterfaceWrapper) GetAuth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAuth(c)
}

// GetEnvironments operation middleware
func (siw *ServerInterfaceWrapper) GetEnvironments(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetEnvironments(c)
}

// GetLogout operation middleware
func (siw *ServerInterfaceWrapper) GetLogout(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLogout(c)
}

// GetProfile operation middleware
func (siw *ServerInterfaceWrapper) GetProfile(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProfile(c)
}

// PostProfile operation middleware
func (siw *ServerInterfaceWrapper) PostProfile(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostProfile(c)
}

// GetProfileAgreements operation middleware
func (siw *ServerInterfaceWrapper) GetProfileAgreements(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProfileAgreements(c)
}

// PostProfileAgreements operation middleware
func (siw *ServerInterfaceWrapper) PostProfileAgreements(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostProfileAgreements(c)
}

// GetProfileTraining operation middleware
func (siw *ServerInterfaceWrapper) GetProfileTraining(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProfileTraining(c)
}

// PostProfileTraining operation middleware
func (siw *ServerInterfaceWrapper) PostProfileTraining(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostProfileTraining(c)
}

// GetProjects operation middleware
func (siw *ServerInterfaceWrapper) GetProjects(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProjects(c)
}

// GetProjectsTre operation middleware
func (siw *ServerInterfaceWrapper) GetProjectsTre(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProjectsTre(c)
}

// PostProjectsTre operation middleware
func (siw *ServerInterfaceWrapper) PostProjectsTre(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostProjectsTre(c)
}

// PostProjectsTreAdminProjectIdApprove operation middleware
func (siw *ServerInterfaceWrapper) PostProjectsTreAdminProjectIdApprove(c *gin.Context) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId string

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostProjectsTreAdminProjectIdApprove(c, projectId)
}

// GetProjectsTreProjectId operation middleware
func (siw *ServerInterfaceWrapper) GetProjectsTreProjectId(c *gin.Context) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId string

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProjectsTreProjectId(c, projectId)
}

// PutProjectsTreProjectId operation middleware
func (siw *ServerInterfaceWrapper) PutProjectsTreProjectId(c *gin.Context) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId string

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutProjectsTreProjectId(c, projectId)
}

// PatchProjectsTreProjectIdPending operation middleware
func (siw *ServerInterfaceWrapper) PatchProjectsTreProjectIdPending(c *gin.Context) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId string

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", c.Param("projectId"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchProjectsTreProjectIdPending(c, projectId)
}

// GetStudies operation middleware
func (siw *ServerInterfaceWrapper) GetStudies(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetStudiesParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", c.Request.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStudies(c, params)
}

// PostStudies operation middleware
func (siw *ServerInterfaceWrapper) PostStudies(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostStudies(c)
}

// PostStudiesAdminStudyIdReview operation middleware
func (siw *ServerInterfaceWrapper) PostStudiesAdminStudyIdReview(c *gin.Context) {

	var err error

	// ------------- Path parameter "studyId" -------------
	var studyId string

	err = runtime.BindStyledParameterWithOptions("simple", "studyId", c.Param("studyId"), &studyId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter studyId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostStudiesAdminStudyIdReview(c, studyId)
}

// GetStudiesStudyId operation middleware
func (siw *ServerInterfaceWrapper) GetStudiesStudyId(c *gin.Context) {

	var err error

	// ------------- Path parameter "studyId" -------------
	var studyId string

	err = runtime.BindStyledParameterWithOptions("simple", "studyId", c.Param("studyId"), &studyId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter studyId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStudiesStudyId(c, studyId)
}

// PutStudiesStudyId operation middleware
func (siw *ServerInterfaceWrapper) PutStudiesStudyId(c *gin.Context) {

	var err error

	// ------------- Path parameter "studyId" -------------
	var studyId string

	err = runtime.BindStyledParameterWithOptions("simple", "studyId", c.Param("studyId"), &studyId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter studyId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutStudiesStudyId(c, studyId)
}

// GetStudiesStudyIdAgreements operation middleware
func (siw *ServerInterfaceWrapper) GetStudiesStudyIdAgreements(c *gin.Context) {

	var err error

	// ------------- Path parameter "studyId" -------------
	var studyId string

	err = runtime.BindStyledParameterWithOptions("simple", "studyId", c.Param("studyId"), &studyId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter studyId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStudiesStudyIdAgreements(c, studyId)
}

// PostStudiesStudyIdAgreements operation middleware
func (siw *ServerInterfaceWrapper) PostStudiesStudyIdAgreements(c *gin.Context) {

	var err error

	// ------------- Path parameter "studyId" -------------
	var studyId string

	err = runtime.BindStyledParameterWithOptions("simple", "studyId", c.Param("studyId"), &studyId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter studyId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostStudiesStudyIdAgreements(c, studyId)
}

// GetStudiesStudyIdAssets operation middleware
func (siw *ServerInterfaceWrapper) GetStudiesStudyIdAssets(c *gin.Context) {

	var err error

	// ------------- Path parameter "studyId" -------------
	var studyId string

	err = runtime.BindStyledParameterWithOptions("simple", "studyId", c.Param("studyId"), &studyId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter studyId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStudiesStudyIdAssets(c, studyId)
}

// PostStudiesStudyIdAssets operation middleware
func (siw *ServerInterfaceWrapper) PostStudiesStudyIdAssets(c *gin.Context) {

	var err error

	// ------------- Path parameter "studyId" -------------
	var studyId string

	err = runtime.BindStyledParameterWithOptions("simple", "studyId", c.Param("studyId"), &studyId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter studyId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostStudiesStudyIdAssets(c, studyId)
}

// GetStudiesStudyIdAssetsAssetId operation middleware
func (siw *ServerInterfaceWrapper) GetStudiesStudyIdAssetsAssetId(c *gin.Context) {

	var err error

	// ------------- Path parameter "studyId" -------------
	var studyId string

	err = runtime.BindStyledParameterWithOptions("simple", "studyId", c.Param("studyId"), &studyId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter studyId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "assetId" -------------
	var assetId string

	err = runtime.BindStyledParameterWithOptions("simple", "assetId", c.Param("assetId"), &assetId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter assetId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStudiesStudyIdAssetsAssetId(c, studyId, assetId)
}

// GetStudiesStudyIdContracts operation middleware
func (siw *ServerInterfaceWrapper) GetStudiesStudyIdContracts(c *gin.Context) {

	var err error

	// ------------- Path parameter "studyId" -------------
	var studyId string

	err = runtime.BindStyledParameterWithOptions("simple", "studyId", c.Param("studyId"), &studyId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter studyId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStudiesStudyIdContracts(c, studyId)
}

// PostStudiesStudyIdContractsUpload operation middleware
func (siw *ServerInterfaceWrapper) PostStudiesStudyIdContractsUpload(c *gin.Context) {

	var err error

	// ------------- Path parameter "studyId" -------------
	var studyId string

	err = runtime.BindStyledParameterWithOptions("simple", "studyId", c.Param("studyId"), &studyId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter studyId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostStudiesStudyIdContractsUpload(c, studyId)
}

// PutStudiesStudyIdContractsContractId operation middleware
func (siw *ServerInterfaceWrapper) PutStudiesStudyIdContractsContractId(c *gin.Context) {

	var err error

	// ------------- Path parameter "studyId" -------------
	var studyId string

	err = runtime.BindStyledParameterWithOptions("simple", "studyId", c.Param("studyId"), &studyId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter studyId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "contractId" -------------
	var contractId string

	err = runtime.BindStyledParameterWithOptions("simple", "contractId", c.Param("contractId"), &contractId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter contractId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutStudiesStudyIdContractsContractId(c, studyId, contractId)
}

// GetStudiesStudyIdContractsContractIdDownload operation middleware
func (siw *ServerInterfaceWrapper) GetStudiesStudyIdContractsContractIdDownload(c *gin.Context) {

	var err error

	// ------------- Path parameter "studyId" -------------
	var studyId string

	err = runtime.BindStyledParameterWithOptions("simple", "studyId", c.Param("studyId"), &studyId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter studyId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "contractId" -------------
	var contractId string

	err = runtime.BindStyledParameterWithOptions("simple", "contractId", c.Param("contractId"), &contractId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter contractId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStudiesStudyIdContractsContractIdDownload(c, studyId, contractId)
}

// PatchStudiesStudyIdPending operation middleware
func (siw *ServerInterfaceWrapper) PatchStudiesStudyIdPending(c *gin.Context) {

	var err error

	// ------------- Path parameter "studyId" -------------
	var studyId string

	err = runtime.BindStyledParameterWithOptions("simple", "studyId", c.Param("studyId"), &studyId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter studyId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchStudiesStudyIdPending(c, studyId)
}

// GetUsers operation middleware
func (siw *ServerInterfaceWrapper) GetUsers(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersParams

	// ------------- Required query parameter "find" -------------

	if paramValue := c.Query("find"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument find is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "find", c.Request.URL.Query(), &params.Find)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter find: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsers(c, params)
}

// PostUsersApprovedResearchersImportCsv operation middleware
func (siw *ServerInterfaceWrapper) PostUsersApprovedResearchersImportCsv(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostUsersApprovedResearchersImportCsv(c)
}

// PostUsersInvite operation middleware
func (siw *ServerInterfaceWrapper) PostUsersInvite(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostUsersInvite(c)
}

// PutUsersUserIdAttributes operation middleware
func (siw *ServerInterfaceWrapper) PutUsersUserIdAttributes(c *gin.Context) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutUsersUserIdAttributes(c, userId)
}

// PostUsersUserIdTraining operation middleware
func (siw *ServerInterfaceWrapper) PostUsersUserIdTraining(c *gin.Context) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostUsersUserIdTraining(c, userId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/agreements/:agreementType", wrapper.GetAgreementsAgreementType)
	router.GET(options.BaseURL+"/auth", wrapper.GetAuth)
	router.GET(options.BaseURL+"/environments", wrapper.GetEnvironments)
	router.GET(options.BaseURL+"/logout", wrapper.GetLogout)
	router.GET(options.BaseURL+"/profile", wrapper.GetProfile)
	router.POST(options.BaseURL+"/profile", wrapper.PostProfile)
	router.GET(options.BaseURL+"/profile/agreements", wrapper.GetProfileAgreements)
	router.POST(options.BaseURL+"/profile/agreements", wrapper.PostProfileAgreements)
	router.GET(options.BaseURL+"/profile/training", wrapper.GetProfileTraining)
	router.POST(options.BaseURL+"/profile/training", wrapper.PostProfileTraining)
	router.GET(options.BaseURL+"/projects", wrapper.GetProjects)
	router.GET(options.BaseURL+"/projects/tre", wrapper.GetProjectsTre)
	router.POST(options.BaseURL+"/projects/tre", wrapper.PostProjectsTre)
	router.POST(options.BaseURL+"/projects/tre/admin/:projectId/approve", wrapper.PostProjectsTreAdminProjectIdApprove)
	router.GET(options.BaseURL+"/projects/tre/:projectId", wrapper.GetProjectsTreProjectId)
	router.PUT(options.BaseURL+"/projects/tre/:projectId", wrapper.PutProjectsTreProjectId)
	router.PATCH(options.BaseURL+"/projects/tre/:projectId/pending", wrapper.PatchProjectsTreProjectIdPending)
	router.GET(options.BaseURL+"/studies", wrapper.GetStudies)
	router.POST(options.BaseURL+"/studies", wrapper.PostStudies)
	router.POST(options.BaseURL+"/studies/admin/:studyId/review", wrapper.PostStudiesAdminStudyIdReview)
	router.GET(options.BaseURL+"/studies/:studyId", wrapper.GetStudiesStudyId)
	router.PUT(options.BaseURL+"/studies/:studyId", wrapper.PutStudiesStudyId)
	router.GET(options.BaseURL+"/studies/:studyId/agreements", wrapper.GetStudiesStudyIdAgreements)
	router.POST(options.BaseURL+"/studies/:studyId/agreements", wrapper.PostStudiesStudyIdAgreements)
	router.GET(options.BaseURL+"/studies/:studyId/assets", wrapper.GetStudiesStudyIdAssets)
	router.POST(options.BaseURL+"/studies/:studyId/assets", wrapper.PostStudiesStudyIdAssets)
	router.GET(options.BaseURL+"/studies/:studyId/assets/:assetId", wrapper.GetStudiesStudyIdAssetsAssetId)
	router.GET(options.BaseURL+"/studies/:studyId/contracts", wrapper.GetStudiesStudyIdContracts)
	router.POST(options.BaseURL+"/studies/:studyId/contracts/upload", wrapper.PostStudiesStudyIdContractsUpload)
	router.PUT(options.BaseURL+"/studies/:studyId/contracts/:contractId", wrapper.PutStudiesStudyIdContractsContractId)
	router.GET(options.BaseURL+"/studies/:studyId/contracts/:contractId/download", wrapper.GetStudiesStudyIdContractsContractIdDownload)
	router.PATCH(options.BaseURL+"/studies/:studyId/pending", wrapper.PatchStudiesStudyIdPending)
	router.GET(options.BaseURL+"/users", wrapper.GetUsers)
	router.POST(options.BaseURL+"/users/approved-researchers/import/csv", wrapper.PostUsersApprovedResearchersImportCsv)
	router.POST(options.BaseURL+"/users/invite", wrapper.PostUsersInvite)
	router.PUT(options.BaseURL+"/users/:userId/attributes", wrapper.PutUsersUserIdAttributes)
	router.POST(options.BaseURL+"/users/:userId/training", wrapper.PostUsersUserIdTraining)
}
