openapi: "3.0.0"
info:
  version: 0.0.0
  title: portal
  description: UCL ARC portal web API
servers:
  - url: /api/v0

paths:
  /profile:
    get:
      description: Users profile
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProfileResponse"
        default:
          description: Unexpected error
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProfileResponse"
  /profile/agreements:
    get:
      description: Get all the agreements a user has agreed to
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProfileAgreements"
        "500":
          description: Internal server error
        default:
          description: Unexpected error
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AgreementConfirmation"

  /agreements/approved-researcher:
    get:
      description: Get the latest approved researcher agreement
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Agreement"
        "406":
          description: Not acceptable
        "500":
          description: Internal server error
        default:
          description: Unexpected error

components:
  schemas:
    ProfileResponse:
      type: object
      required:
        - username
        - roles
        - chosen_name
      properties:
        username:
          type: string
        roles:
          type: array
          items:
            type: string
        chosen_name:
          type: string

    Agreement:
      type: object
      required:
        - id
        - text
      properties:
        id:
          type: string
          description: UUID of the agreement
        text:
          type: string

    AgreementConfirmation:
      type: object
      required:
        - agreement_id
      properties:
        agreement_id:
          type: string
          description: UUID of the agreement that has been agreed to

    ConfirmedAgreement:
      type: object
      required:
        - confirmed_at
        - agreement_type
      properties:
        confirmed_at:
          type: string
          description: Time in RFC3339 format at which the agreement was confirmed
        agreement_type:
          type: string
          description: Type of agreement that was confirmed

    ProfileAgreements:
      type: object
      required:
        - confirmed_agreements
      properties:
        confirmed_agreements:
          type: array
          items:
            $ref: "#/components/schemas/ConfirmedAgreement"
