openapi: "3.0.0"
info:
  version: 0.0.0
  title: portal
  description: UCL ARC portal web API
servers:
  - url: /api/v0

paths:
  /auth:
    get:
      description: Authentication and authorization status of the user
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Auth"
        "401":
          description: Unauthenticated
        "500":
          description: Internal server error
        default:
          description: Unexpected error

  /profile:
    get:
      description: Users profile
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProfileResponse"
        default:
          description: Unexpected error
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProfileUpdate"
      responses:
        "200":
          description: "Successfully updated profile"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProfileResponse"
        "500":
          description: Internal server error
        default:
          description: Unexpected error

  /profile/agreements:
    get:
      description: Get all the agreements a user has agreed to
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProfileAgreements"
        "500":
          description: Internal server error
        default:
          description: Unexpected error
    post:
      description: Update the agreements for a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AgreementConfirmation"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProfileAgreements"
        "500":
          description: Internal server error
        default:
          description: Unexpected error

  /profile/training:
    post:
      description: Update the training record for a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProfileTrainingUpdate"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProfileTrainingResponse"
          description: Accepted
        "500":
          description: Internal server error
        default:
          description: Unexpected error

  /agreements/approved-researcher:
    get:
      description: Get the latest approved researcher agreement
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Agreement"
        "406":
          description: Not acceptable
        "500":
          description: Internal server error
        default:
          description: Unexpected error

  /people:
    get:
      description: Get all the people a user has access to
      responses:
        "200":
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/People_AdminResponse"
                  - $ref: "#/components/schemas/People_ApprovedResearcherResponse"
        "500":
          description: Internal server error
        default:
          description: Unexpected error

components:
  schemas:
    Auth:
      type: object
      required:
        - username
        - roles
      properties:
        username:
          type: string
        roles:
          type: array
          items:
            type: string

    ProfileResponse:
      type: object
      required:
        - username
        - chosen_name
      properties:
        username:
          type: string
        chosen_name:
          type: string

    ProfileUpdate:
      type: object
      required:
        - chosen_name
      properties:
        chosen_name:
          type: string

    Agreement:
      type: object
      required:
        - id
        - text
      properties:
        id:
          type: string
          description: UUID of the agreement
        text:
          type: string

    AgreementConfirmation:
      type: object
      required:
        - agreement_id
      properties:
        agreement_id:
          type: string
          description: UUID of the agreement that has been agreed to

    ConfirmedAgreement:
      type: object
      required:
        - confirmed_at
        - agreement_type
      properties:
        confirmed_at:
          type: string
          description: Time in RFC3339 format at which the agreement was confirmed
        agreement_type:
          type: string
          description: Type of agreement that was confirmed

    ProfileAgreements:
      type: object
      required:
        - confirmed_agreements
      properties:
        confirmed_agreements:
          type: array
          items:
            $ref: "#/components/schemas/ConfirmedAgreement"

    ProfileTrainingUpdate:
      type: object
      required:
        - kind
      properties:
        kind:
          type: string
          enum: [training_kind_nhsd]
        certficate_content_pdf_base64:
          type: string
          description: Base64 encoded PDF file data of the certificate

    ProfileTrainingResponse:
      type: object
      properties:
        certificate_is_valid:
          type: boolean
          description: Is the certificate valid
        certificate_message:
          type: string
          description: Reason why the training certificate is valid/invalid
        certificate_issued_at:
          type: string
          description: Time in RFC3339 format at which the the certificate was issued

    Person_AdminView:
      type: object
      required:
        - user
        - roles
        - agreements
      properties:
        user:
          type: object
          properties:
            username:
              type: string
            id:
              type: string
        roles:
          type: array
          items:
            type: string
        agreements:
          $ref: "#/components/schemas/ProfileAgreements"

    People_AdminResponse:
      type: object
      required:
        - people
      properties:
        people:
          type: array
          items:
            $ref: "#/components/schemas/Person_AdminView"

    People_ApprovedResearcherResponse:
      type: object
      required:
        - people
      properties:
        people:
          type: array
          items:
            type: string
            description: Placeholder response until projects are implemented
