openapi: "3.0.0"
info:
  version: 0.0.0
  title: portal
  description: UCL ARC portal web API
servers:
  - url: /api/v0

paths:
  /auth:
    get:
      description: Authentication and authorization status of the user
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Auth"
        "401":
          description: Unauthenticated
        "500":
          description: Internal server error
        default:
          description: Unexpected error

  /profile:
    get:
      description: Users profile
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Profile"
        default:
          description: Unexpected error
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProfileUpdate"
      responses:
        "200":
          description: "Successfully updated profile"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Profile"
        "500":
          description: Internal server error
        default:
          description: Unexpected error

  /profile/agreements:
    get:
      description: Get all the agreements a user has agreed to
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserAgreements"
        "500":
          description: Internal server error
        default:
          description: Unexpected error
    post:
      description: Update the agreements for a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AgreementConfirmation"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserAgreements"
        "500":
          description: Internal server error
        default:
          description: Unexpected error

  /profile/training:
    get:
      description: Get the training record status for a user
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProfileTraining"
        "500":
          description: Internal server error
        default:
          description: Unexpected error
    post:
      description: Update the training record for a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProfileTrainingUpdate"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProfileTrainingResponse"
          description: Accepted
        "500":
          description: Internal server error
        default:
          description: Unexpected error

  /agreements/{agreementType}:
    get:
      description: Get the latest approved researcher agreement
      parameters:
        - in: path
          name: agreementType
          required: true
          description: Type of agreement to get
          schema:
            $ref: "#/components/schemas/AgreementType"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Agreement"
        "406":
          description: Not acceptable
        "500":
          description: Internal server error
        default:
          description: Unexpected error

  /users:
    get:
      description: Get all the users a user has access to view
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserData"
        "403":
          description: Forbidden
        "500":
          description: Internal server error
        default:
          description: Unexpected error

  /users/{userId}/training:
    post:
      parameters:
        - in: path
          name: userId
          required: true
          description: ID of the user to be updated
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserTrainingUpdate"
      responses:
        "200":
          description: Successfully updated user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TrainingRecord"
        "403":
          description: Forbidden
        "404":
          description: Not found
        "500":
          description: Internal server error
        default:
          description: Unexpected error

  /users/approved-researchers/import/csv:
    post:
      description: |
        Upload a CSV file with fields
        <username: string, e.g. "bob@example.com">,
        <agreed to agreement: bool, e.g. true>,
        <NHSD training completed at date: string, e.g. 2021-03-11>
      requestBody:
        required: true
        content:
          text/csv:
            schema:
              type: string
              format: binary
      responses:
        "204":
          description: OK
        "403":
          description: Forbidden
        "500":
          description: Internal server error
        default:
          description: Unexpected error

  # Asset Management
  /assets:
    get:
      description: Get all assets for the authenticated user
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Asset"
        "500":
          description: Internal server error
        default:
          description: Unexpected error
    post:
      description: Create a new asset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AssetCreate"
      responses:
        "201":
          description: Asset created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Asset"
        "400":
          description: Invalid request
        "500":
          description: Internal server error
        default:
          description: Unexpected error

components:
  schemas:
    Auth:
      type: object
      required:
        - username
        - roles
      properties:
        username:
          type: string
        roles:
          type: array
          items:
            type: string
            enum:
              - admin
              - base
              - approved-researcher

    Profile:
      type: object
      required:
        - username
        - chosen_name
      properties:
        username:
          type: string
        chosen_name:
          type: string

    ProfileUpdate:
      type: object
      required:
        - chosen_name
      properties:
        chosen_name:
          type: string

    Agreement:
      type: object
      required:
        - id
        - text
      properties:
        id:
          type: string
          description: UUID of the agreement
        text:
          type: string

    AgreementConfirmation:
      type: object
      required:
        - agreement_id
      properties:
        agreement_id:
          type: string
          description: UUID of the agreement that has been agreed to

    ConfirmedAgreement:
      type: object
      required:
        - confirmed_at
        - agreement_type
      properties:
        confirmed_at:
          type: string
          description: Time in RFC3339 format at which the agreement was confirmed
        agreement_type:
          $ref: "#/components/schemas/AgreementType"
          description: Type of agreement that was confirmed

    AgreementType:
      type: string
      enum:
        - approved-researcher
        - study-owner

    UserAgreements:
      type: object
      required:
        - confirmed_agreements
      properties:
        confirmed_agreements:
          type: array
          items:
            $ref: "#/components/schemas/ConfirmedAgreement"

    TrainingKind:
      type: string
      enum:
        - training_kind_nhsd

    ProfileTrainingUpdate:
      type: object
      required:
        - kind
      properties:
        kind:
          $ref: "#/components/schemas/TrainingKind"
        certificate_content_pdf_base64:
          type: string
          description: Base64 encoded PDF file data of the certificate

    ProfileTrainingResponse:
      type: object
      properties:
        certificate_is_valid:
          type: boolean
          description: Is the certificate valid
        certificate_message:
          type: string
          description: Reason why the training certificate is valid/invalid
        certificate_issued_at:
          type: string
          description: Time in RFC3339 format at which the the certificate was issued

    TrainingRecord:
      type: object
      required:
        - kind
        - is_valid
      properties:
        kind:
          $ref: "#/components/schemas/TrainingKind"
          description: The type of training
        is_valid:
          type: boolean
          description: Whether this training certification is currently valid
        completed_at:
          type: string
          description: Time in RFC3339 format when the training was completed

    ProfileTraining:
      type: object
      required:
        - training_records
      properties:
        training_records:
          type: array
          items:
            $ref: "#/components/schemas/TrainingRecord"
          description: List of all training records for the user

    User:
      type: object
      required:
        - username
        - id
      properties:
        username:
          type: string
        id:
          type: string

    UserData:
      type: object
      required:
        - user
        - roles
        - agreements
        - training_record
      properties:
        user:
          $ref: "#/components/schemas/User"
        roles:
          type: array
          items:
            type: string
        agreements:
          $ref: "#/components/schemas/UserAgreements"
        training_record:
          $ref: "#/components/schemas/ProfileTraining"

    UserTrainingUpdate:
      type: object
      required:
        - training_kind
        - training_date
      properties:
        training_kind:
          $ref: "#/components/schemas/TrainingKind"
        training_date:
          type: string
          description: Time in RFC3339 format at which the the certificate was issued

    Asset:
      type: object
      description: A data asset representing a set of related data entities
      required:
        - id
        - title
        - description
        - classification_impact
        - location
        - is_active
        - protection
        - created_at
        - updated_at
      properties:
        id:
          type: string
          description: Unique identifier for the asset
        title:
          type: string
          description: Title of the asset
        description:
          type: string
          description: Description of the asset
        classification_impact:
          type: integer
          minimum: 1
          maximum: 5
          description: Classification impact level from 1-5
        location:
          type: string
          description: Location of the asset
        is_active:
          type: boolean
          description: Whether the asset is active or inactive
        protection:
          type: string
          enum:
            - anonymisation
            - identifiable_low_confidence_pseudonymisation
          description: Type of protection applied to the asset
        legal_basis:
          type: string
          description: Legal basis for holding the asset
        format:
          type: string
          description: Format of the asset
        expiry:
          type: string
          description: Retention expiry date of the asset
        created_at:
          type: string
          description: Time in RFC3339 format when the asset was created
        updated_at:
          type: string
          description: Time in RFC3339 format when the asset was last updated

    AssetCreate:
      type: object
      description: Data required to create a new asset
      required:
        - title
        - description
        - classification_impact
        - location
        - is_active
        - protection
      properties:
        title:
          type: string
          description: Title of the asset
        description:
          type: string
          description: Description of the asset
        classification_impact:
          type: integer
          minimum: 1
          maximum: 5
          description: Classification impact level from 1-5
        location:
          type: string
          description: Location of the asset
        is_active:
          type: boolean
          description: Whether the asset is active or inactive
        protection:
          type: string
          enum:
            - anonymisation
            - identifiable_low_confidence_pseudonymisation
          description: Type of protection applied to the asset
        legal_basis:
          type: string
          description: Legal basis for holding the asset
        format:
          type: string
          description: Format of the asset
        expiry:
          type: string
          description: Retention expiry date of the asset
