FROM cypress/included:14.3.0

# Set working directory
WORKDIR /web

# Copy everything at once (including cypress.config.mjs and source files)
COPY web .

# Install deps
RUN npm ci

# Default command
CMD ["npx", "cypress", "run", "--config-file", "cypress.config.mjs"]
