# This file is used to spin up the dev environment for the Go web API and React frontend.

# Dev API
FROM golang:1.24.2-alpine AS web-api-dev
RUN go install github.com/air-verse/air@latest
WORKDIR /repo
ENV GIN_MODE="debug"
CMD ["air", "--build.cmd", "go build -o bin/web-api cmd/web-api/main.go", "--build.bin", "./bin/web-api", "--build.exclude_dir", "web,bin,deploy,tmp"]

# Dev frontend
FROM node:22-alpine3.20 AS web-frontend-dev
WORKDIR /repo/web
COPY web/package.json .
RUN npm install
CMD [ "npm", "run", "dev", "--", "--host", "0.0.0.0" ]
