// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ProjectUpdateStatus.
const (
	Deleted  ProjectUpdateStatus = "deleted"
	Deployed ProjectUpdateStatus = "deployed"
)

// Valid indicates whether the value is a known member of the ProjectUpdateStatus enum.
func (e ProjectUpdateStatus) Valid() bool {
	switch e {
	case Deleted:
		return true
	case Deployed:
		return true
	default:
		return false
	}
}

// Defines values for VMImagePlatform.
const (
	Aws       VMImagePlatform = "aws"
	Condenser VMImagePlatform = "condenser"
)

// Valid indicates whether the value is a known member of the VMImagePlatform enum.
func (e VMImagePlatform) Valid() bool {
	switch e {
	case Aws:
		return true
	case Condenser:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Ping defines model for Ping.
type Ping struct {
	Message string `json:"message"`
}

// ProjectUpdate defines model for ProjectUpdate.
type ProjectUpdate struct {
	// DeployedVersionUpdatedAt Value of the updated_at field that the deployed version is, in RFC3339 format
	DeployedVersionUpdatedAt string `json:"deployed_version_updated_at"`

	// Status Current status of the project in the TRE
	Status ProjectUpdateStatus `json:"status"`
}

// ProjectUpdateStatus Current status of the project in the TRE
type ProjectUpdateStatus string

// UserStatus defines model for UserStatus.
type UserStatus struct {
	// IsApprovedResearcher Is the user an approved researcher?
	IsApprovedResearcher bool `json:"is_approved_researcher"`

	// NhsdTrainingExpiresAt Instant at which the user's training expires in RFC3339 format
	NhsdTrainingExpiresAt *string `json:"nhsd_training_expires_at,omitempty"`
}

// VMImage defines model for VMImage.
type VMImage struct {
	Description string `json:"description"`

	// Id e.g. AMI id
	Id       string          `json:"id"`
	Name     string          `json:"name"`
	Platform VMImagePlatform `json:"platform"`
}

// VMImagePlatform defines model for VMImage.Platform.
type VMImagePlatform string

// InvalidObject defines model for InvalidObject.
type InvalidObject = Error

// GetUserStatusParams defines parameters for GetUserStatus.
type GetUserStatusParams struct {
	// Username Username of the user to get the status of. e.g. ccxyz@ucl.ac.uk
	Username string `form:"username" json:"username"`
}

// PostProjectsProjectNameJSONRequestBody defines body for PostProjectsProjectName for application/json ContentType.
type PostProjectsProjectNameJSONRequestBody = ProjectUpdate

// PostVmImagesJSONRequestBody defines body for PostVmImages for application/json ContentType.
type PostVmImagesJSONRequestBody = VMImage

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetPing Ping to check connectivity and auth
	// (GET /ping)
	GetPing(c *gin.Context)

	// (POST /projects/{projectName})
	PostProjectsProjectName(c *gin.Context, projectName string)

	// (GET /user-status)
	GetUserStatus(c *gin.Context, params GetUserStatusParams)

	// (POST /vm-images)
	PostVmImages(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetPing operation middleware
func (siw *ServerInterfaceWrapper) GetPing(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPing(c)
}

// PostProjectsProjectName operation middleware
func (siw *ServerInterfaceWrapper) PostProjectsProjectName(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "projectName" -------------
	var projectName string

	err = runtime.BindStyledParameterWithOptions("simple", "projectName", c.Param("projectName"), &projectName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter projectName: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostProjectsProjectName(c, projectName)
}

// GetUserStatus operation middleware
func (siw *ServerInterfaceWrapper) GetUserStatus(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserStatusParams

	// ------------- Required query parameter "username" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "username", c.Request.URL.Query(), &params.Username, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter username: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUserStatus(c, params)
}

// PostVmImages operation middleware
func (siw *ServerInterfaceWrapper) PostVmImages(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostVmImages(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/ping", wrapper.GetPing)
	router.GET(options.BaseURL+"/user-status", wrapper.GetUserStatus)
	router.POST(options.BaseURL+"/vm-images", wrapper.PostVmImages)
	router.POST(options.BaseURL+"/projects/:projectName", wrapper.PostProjectsProjectName)
}
