services:
  web-api:
    build:
      context: ../..
      target: web-api-dev
    restart: always
    environment:
      DEBUG: true
      PORT: "8080"
      IS_DEV_DEPLOY: true
      ADMIN_USERNAMES: "cceatyo-test@arctretest.onmicrosoft.com,ccaeaho@ucl.ac.uk,cceajeh@ucl.ac.uk"
      DATABASE_DSN: host=postgres user=postgres password=postgres dbname=dev sslmode=disable TimeZone=UTC # pragma: allowlist secret
    volumes:
      - type: bind
        source: ../..
        target: /repo

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.8.2
    command: --config /oauth2-proxy.cfg
    hostname: oauth2-proxy
    volumes:
      - "./oauth2-proxy.cfg:/oauth2-proxy.cfg:ro"
    restart: unless-stopped
    depends_on:
      - web-api

  web-frontend:
    build:
      context: ../..
      target: web-frontend-dev
    restart: on-failure
    volumes:
      - type: bind
        source: ../..
        target: /repo
      - type: volume
        target: /repo/web/node_modules

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web-api
      - web-frontend

  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres # pragma: allowlist secret
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
