services:
  web-api:
    build:
      context: ../..
      target: web-api-dev
    restart: always
    environment:
      DEBUG: true
      PORT: "8080"
      IS_DEV_DEPLOY: true
      DATABASE_URL: postgres://postgres:postgres@db:5432/dev?sslmode=disable # pragma: allowlist secret
    volumes:
      - type: bind
        source: ../..
        target: /repo
    depends_on:
      - db

  web-frontend:
    build:
      context: ../..
      target: web-frontend-dev
    restart: on-failure
    volumes:
      - type: bind
        source: ../..
        target: /repo
      - type: volume
        target: /repo/web/node_modules

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web-api
      - web-frontend

  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres # pragma: allowlist secret
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
