services:

  postgres-test:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres # pragma: allowlist secret
      POSTGRES_DB: test
    tmpfs:
      - /var/lib/postgresql/data  # fast + wiped every run (perfect for tests)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      retries: 10


  integration-tests:
    build:
      context: ../..
      target: api-dev   # reuse existing Go dev image
    depends_on:
      postgres-test:
        condition: service_healthy
    environment:
      DATABASE_URL: host=postgres-test port=5432 user=postgres password=postgres dbname=test sslmode=disable # pragma: allowlist secret
    volumes:
      - type: bind
        source: ../..  # actual project folder on your laptop
        target: /repo  # where it appears inside the container, it is just an internal path, not tied to the real repo name
    working_dir: /repo
    command:
      - go
      - test
      - ./internal/service/...
      - -tags=integration
      - -v
