// This file is auto-generated by @hey-api/openapi-ts

export type ProfileResponse = {
    username: string;
    roles: Array<string>;
};

export type GetProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/profile';
};

export type GetProfileErrors = {
    /**
     * Unexpected error
     */
    default: unknown;
};

export type GetProfileResponses = {
    200: ProfileResponse;
};

export type GetProfileResponse = GetProfileResponses[keyof GetProfileResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v0` | (string & {});
};