// Package myservices provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package myservices

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for Channel.
const (
	Chat  Channel = "Chat"
	Email Channel = "Email"
	Voice Channel = "Voice"
)

// Valid indicates whether the value is a known member of the Channel enum.
func (e Channel) Valid() bool {
	switch e {
	case Chat:
		return true
	case Email:
		return true
	case Voice:
		return true
	default:
		return false
	}
}

// Defines values for Source.
const (
	ContactCentre Source = "Contact Centre"
	InsideUCL     Source = "InsideUCL"
	MyHR          Source = "MyHR"
	Norman        Source = "Norman"
)

// Valid indicates whether the value is a known member of the Source enum.
func (e Source) Valid() bool {
	switch e {
	case ContactCentre:
		return true
	case InsideUCL:
		return true
	case MyHR:
		return true
	case Norman:
		return true
	default:
		return false
	}
}

// AttachmentResponseSchema defines model for attachmentResponseSchema.
type AttachmentResponseSchema struct {
	// Response Response object containing request details.
	Response *struct {
		// Request Details of the created request.
		Request *struct {
			// Attachments List of attachments for the request.  The key name for each attachment is the attachment id as will appear in custom fields of attachment type.
			Attachments *map[string]struct {
				// Filename filename of attachment
				//
				// Example: test.pdf
				Filename *string `json:"filename,omitempty"`

				// Id Internal id of the attachment record
				//
				// Example: 123456
				Id *int `json:"id,omitempty"`

				// Url A temporary url that can be used to download the attachment content.  This be valid for no more than 1 hour.  TODO: check this.
				Url *string `json:"url,omitempty"`
			} `json:"attachments,omitempty"`

			// Identifier Unique identifier for the request.
			//
			// Example: 819185
			Identifier *int `json:"identifier,omitempty"`
		} `json:"request,omitempty"`
	} `json:"response,omitempty"`
}

// Channel Medium of interaction to create a Request
//
// Example: Chat
type Channel string

// Error defines model for error.
type Error struct {
	// Code Error code.
	//
	// Example: REQ_NOT_FOUND
	Code *string `json:"code,omitempty"`

	// Message Error message.
	//
	// Example: Request not found
	Message *string `json:"message,omitempty"`

	// Timestamp Timestamp of the error.
	//
	// Example: 2024-07-08T16:11:23+01:00
	Timestamp *string `json:"timestamp,omitempty"`
}

// RequestBodySchema Details of the service request.
type RequestBodySchema struct {
	// Channel Medium of interaction to create a Request
	//
	// Example: Chat
	Channel *Channel `json:"channel,omitempty"`

	// CustomFields Custom fields specific to the request. This can contain any fields
	//
	// Example: {"assignment_leaving_reason":"Ill Health Retirement","dt_number":"292897","employee_name":"Example Person","logged_at":"12/07/2024 19:12","norman_ref":"CAS-495789-J2G5Y8","origin":"Phone","transaction_status":"On Approval (HR)"}
	CustomFields *map[string]interface{} `json:"custom_fields,omitempty"`

	// RequestedByEmail Email address of person making the request. Used to lookup a person record in MyServices. Can be used as alternative to requested_by_upi.  If a ucl address, the form of userid@ucl.ac.uk is recommended over alias.
	//
	// Example: abc123@abc.com
	RequestedByEmail *string `json:"requested_by_email,omitempty"`

	// RequestedByUpi UPI of person making the request. Used to lookup a person record in MyServices. If blank defaults to a system account.  requested_by_upi takes precedence over requested_by_email.
	//
	// Example: ABC123
	RequestedByUpi *string `json:"requested_by_upi,omitempty"`

	// RequestedForEmail Email address of person the request is for. If blank defaults to requested_by_email. Can be used as alternative to requested_for_upi.  If a ucl address, the form of userid@ucl.ac.uk is recommended over alias.
	//
	// Example: abc123@abc.com
	RequestedForEmail *string `json:"requested_for_email,omitempty"`

	// RequestedForUpi UPI of person the request is for. If blank defaults to requested_by_upi.  requested_for_upi takes precedence over requested_for_email.
	//
	// Example: ABC123
	RequestedForUpi *string `json:"requested_for_upi,omitempty"`

	// ServiceInstance Service instance associated with the request.
	//
	// Example: HR - Employee Management
	ServiceInstance *string `json:"service_instance,omitempty"`

	// Source Source of the request, this will be the name of a UCL service where appropriate
	//
	// Example: Contact Centre
	Source *Source `json:"source,omitempty"`

	// SourceId A unique id for this request in the source system
	//
	// Example: ed0eda87-9fbc-4f81-8bd9-2bf2b89e9e5b
	SourceId *string `json:"source_id,omitempty"`

	// Subject Subject of the request.
	//
	// Example: Multi-factor authentication (MFA) > Post Setup
	Subject *string `json:"subject,omitempty"`

	// SupportDomain Domain where the request is created.
	//
	// Example: myservices-hr
	SupportDomain string `json:"support_domain"`

	// TemplateName Name of the template used for the request.
	//
	// Example: hr_rt_leaver
	TemplateName string `json:"template_name"`
}

// RequestResponseSchema defines model for requestResponseSchema.
type RequestResponseSchema struct {
	// Response Response object containing request details.
	Response *struct {
		// Request Details of the created request.
		Request *struct {
			// Channel Medium of interaction to create a Request
			//
			// Example: Chat
			Channel *Channel `json:"channel,omitempty"`

			// CompletionReason Reason for request completion.
			//
			// Example: withdrawn
			CompletionReason *string `json:"completion_reason,omitempty"`

			// CreatedAt Timestamp when the request was created.
			//
			// Example: 2024-07-08T16:11:23+01:00
			CreatedAt *time.Time `json:"created_at,omitempty"`

			// CustomFields Custom fields associated with the request.
			//
			// Example: {"description":"Username: abcde12\n\nTester requires an MFA reset...","logged_at":"12/07/2024 19:12","meaningful_response":"Your case has been passed to the relevant team...","norman_ref":"CAS-495789-J2G5Y8","norman_status":"Escalated"}
			CustomFields *map[string]interface{} `json:"custom_fields,omitempty"`

			// Identifier Unique identifier for the request.
			//
			// Example: 819185
			Identifier *int `json:"identifier,omitempty"`

			// Source Source of the request, this will be the name of a UCL service where appropriate
			//
			// Example: Contact Centre
			Source *Source `json:"source,omitempty"`

			// SourceId A unique id for this request in the source system
			//
			// Example: ed0eda87-9fbc-4f81-8bd9-2bf2b89e9e5b
			SourceId *string `json:"source_id,omitempty"`

			// Status Status of the request.
			//
			// Example: completed
			Status *string `json:"status,omitempty"`

			// Subject Subject of the request.
			//
			// Example: Multi-factor authentication (MFA) > Post Setup
			Subject *string `json:"subject,omitempty"`

			// Team Team responsible for handling the request.
			//
			// Example: Integration Test Team
			Team *string `json:"team,omitempty"`

			// Template Template used for the request.
			//
			// Example: integration_test_template
			Template *string `json:"template,omitempty"`

			// UpdatedAt Timestamp when the request was last updated.
			//
			// Example: 2024-08-16T12:08:02+01:00
			UpdatedAt *time.Time `json:"updated_at,omitempty"`
		} `json:"request,omitempty"`
	} `json:"response,omitempty"`
}

// Source Source of the request, this will be the name of a UCL service where appropriate
//
// Example: Contact Centre
type Source string

// TaskResponseSchema defines model for taskResponseSchema.
type TaskResponseSchema struct {
	// Response Response object containing task details.
	Response *struct {
		// Request Details of the created task.
		Request *struct {
			// CustomFields Custom fields associated with the task.
			//
			// Example: {"details":"The project was created successfully","project_code":123456789}
			CustomFields *map[string]interface{} `json:"custom_fields,omitempty"`

			// Identifier Unique identifier for the task.
			//
			// Example: 819185
			Identifier *int `json:"identifier,omitempty"`

			// Status Status of the task.
			//
			// Example: completed
			Status *string `json:"status,omitempty"`
		} `json:"request,omitempty"`
	} `json:"response,omitempty"`
}

// PatchRequestsIdJSONBody defines parameters for PatchRequestsId.
type PatchRequestsIdJSONBody struct {
	// CompletionReason Reason for the completion of the request.
	//
	// Example: Issue resolved
	CompletionReason *string `json:"completion_reason,omitempty"`

	// Status The new status of the request.
	//
	// Example: completed
	Status *string `json:"status,omitempty"`
}

// PatchTasksIdJSONBody defines parameters for PatchTasksId.
type PatchTasksIdJSONBody struct {
	// CustomFields custom fields to add to the task
	//
	// Example: {"details":"The project was created successfully","project_code":123456789}
	CustomFields *map[string]interface{} `json:"custom_fields,omitempty"`

	// Note A note to add to the task.
	//
	// Example: Task completed successfully
	Note *string `json:"note,omitempty"`

	// Status The new status of the request.
	//
	// Example: completed
	Status *string `json:"status,omitempty"`
}

// PostRequestsJSONRequestBody defines body for PostRequests for application/json ContentType.
type PostRequestsJSONRequestBody = RequestBodySchema

// PatchRequestsIdJSONRequestBody defines body for PatchRequestsId for application/json ContentType.
type PatchRequestsIdJSONRequestBody PatchRequestsIdJSONBody

// PatchTasksIdJSONRequestBody defines body for PatchTasksId for application/json ContentType.
type PatchTasksIdJSONRequestBody PatchTasksIdJSONBody

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetHeartbeat Ping the API
	//
	// Corresponds with GET /heartbeat (the `GetHeartbeat` operationId).
	GetHeartbeat(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostRequestsWithBody Create a new enterprise service request
	//
	// This endpoint allows you to create a new enterprise service request.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /requests (the `PostRequests` operationId).
	PostRequestsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostRequests Create a new enterprise service request
	//
	// This endpoint allows you to create a new enterprise service request.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /requests (the `PostRequests` operationId).
	PostRequests(ctx context.Context, body PostRequestsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetRequestsId Get details of a specific request
	//
	// This endpoint retrieves the details of a service request by its identifier.
	//
	// Corresponds with GET /requests/{id} (the `GetRequestsId` operationId).
	GetRequestsId(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchRequestsIdWithBody Update a specific request
	//
	// This endpoint allows partial updates to a service request by its identifier.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PATCH /requests/{id} (the `PatchRequestsId` operationId).
	PatchRequestsIdWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchRequestsId Update a specific request
	//
	// This endpoint allows partial updates to a service request by its identifier.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PATCH /requests/{id} (the `PatchRequestsId` operationId).
	PatchRequestsId(ctx context.Context, id int, body PatchRequestsIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetRequestsIdAttachments Get attachments specific request
	//
	// This endpoint retrieves the attachments of a service request by its identifier.  This does not include attachments to notes.
	//
	// Corresponds with GET /requests/{id}/attachments (the `GetRequestsIdAttachments` operationId).
	GetRequestsIdAttachments(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchTasksIdWithBody Update a specific task
	//
	// This endpoint allows partial updates to a task by its identifier.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PATCH /tasks/{id} (the `PatchTasksId` operationId).
	PatchTasksIdWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchTasksId Update a specific task
	//
	// This endpoint allows partial updates to a task by its identifier.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PATCH /tasks/{id} (the `PatchTasksId` operationId).
	PatchTasksId(ctx context.Context, id int, body PatchTasksIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetHeartbeat Ping the API
//
// Corresponds with GET /heartbeat (the `GetHeartbeat` operationId).
func (c *Client) GetHeartbeat(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHeartbeatRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostRequestsWithBody Create a new enterprise service request
//
// This endpoint allows you to create a new enterprise service request.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /requests (the `PostRequests` operationId).
func (c *Client) PostRequestsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostRequestsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostRequests Create a new enterprise service request
//
// This endpoint allows you to create a new enterprise service request.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /requests (the `PostRequests` operationId).
func (c *Client) PostRequests(ctx context.Context, body PostRequestsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostRequestsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetRequestsId Get details of a specific request
//
// This endpoint retrieves the details of a service request by its identifier.
//
// Corresponds with GET /requests/{id} (the `GetRequestsId` operationId).
func (c *Client) GetRequestsId(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRequestsIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PatchRequestsIdWithBody Update a specific request
//
// This endpoint allows partial updates to a service request by its identifier.
//
// Takes any type of body and a specified content type.
//
// Corresponds with PATCH /requests/{id} (the `PatchRequestsId` operationId).
func (c *Client) PatchRequestsIdWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchRequestsIdRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PatchRequestsId Update a specific request
//
// This endpoint allows partial updates to a service request by its identifier.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PATCH /requests/{id} (the `PatchRequestsId` operationId).
func (c *Client) PatchRequestsId(ctx context.Context, id int, body PatchRequestsIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchRequestsIdRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetRequestsIdAttachments Get attachments specific request
//
// This endpoint retrieves the attachments of a service request by its identifier.  This does not include attachments to notes.
//
// Corresponds with GET /requests/{id}/attachments (the `GetRequestsIdAttachments` operationId).
func (c *Client) GetRequestsIdAttachments(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRequestsIdAttachmentsRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PatchTasksIdWithBody Update a specific task
//
// This endpoint allows partial updates to a task by its identifier.
//
// Takes any type of body and a specified content type.
//
// Corresponds with PATCH /tasks/{id} (the `PatchTasksId` operationId).
func (c *Client) PatchTasksIdWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchTasksIdRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PatchTasksId Update a specific task
//
// This endpoint allows partial updates to a task by its identifier.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PATCH /tasks/{id} (the `PatchTasksId` operationId).
func (c *Client) PatchTasksId(ctx context.Context, id int, body PatchTasksIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchTasksIdRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetHeartbeatRequest constructs an http.Request for the GetHeartbeat method
func NewGetHeartbeatRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/heartbeat")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostRequestsRequest calls the generic PostRequests builder with application/json body
func NewPostRequestsRequest(server string, body PostRequestsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostRequestsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostRequestsRequestWithBody constructs an http.Request for the PostRequests method, with any body, and a specified content type
func NewPostRequestsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/requests")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetRequestsIdRequest constructs an http.Request for the GetRequestsId method
func NewGetRequestsIdRequest(server string, id int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/requests/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPatchRequestsIdRequest calls the generic PatchRequestsId builder with application/json body
func NewPatchRequestsIdRequest(server string, id int, body PatchRequestsIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchRequestsIdRequestWithBody(server, id, "application/json", bodyReader)
}

// NewPatchRequestsIdRequestWithBody constructs an http.Request for the PatchRequestsId method, with any body, and a specified content type
func NewPatchRequestsIdRequestWithBody(server string, id int, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/requests/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPatch, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetRequestsIdAttachmentsRequest constructs an http.Request for the GetRequestsIdAttachments method
func NewGetRequestsIdAttachmentsRequest(server string, id int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/requests/%s/attachments", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPatchTasksIdRequest calls the generic PatchTasksId builder with application/json body
func NewPatchTasksIdRequest(server string, id int, body PatchTasksIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchTasksIdRequestWithBody(server, id, "application/json", bodyReader)
}

// NewPatchTasksIdRequestWithBody constructs an http.Request for the PatchTasksId method, with any body, and a specified content type
func NewPatchTasksIdRequestWithBody(server string, id int, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tasks/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPatch, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetHeartbeatWithResponse Ping the API
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /heartbeat (the `GetHeartbeat` operationId).
	GetHeartbeatWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHeartbeatResponse, error)

	// PostRequestsWithBodyWithResponse Create a new enterprise service request
	//
	// This endpoint allows you to create a new enterprise service request.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /requests (the `PostRequests` operationId).
	PostRequestsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostRequestsResponse, error)

	// PostRequestsWithResponse Create a new enterprise service request
	//
	// This endpoint allows you to create a new enterprise service request.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /requests (the `PostRequests` operationId).
	PostRequestsWithResponse(ctx context.Context, body PostRequestsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostRequestsResponse, error)

	// GetRequestsIdWithResponse Get details of a specific request
	//
	// This endpoint retrieves the details of a service request by its identifier.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /requests/{id} (the `GetRequestsId` operationId).
	GetRequestsIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*GetRequestsIdResponse, error)

	// PatchRequestsIdWithBodyWithResponse Update a specific request
	//
	// This endpoint allows partial updates to a service request by its identifier.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PATCH /requests/{id} (the `PatchRequestsId` operationId).
	PatchRequestsIdWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchRequestsIdResponse, error)

	// PatchRequestsIdWithResponse Update a specific request
	//
	// This endpoint allows partial updates to a service request by its identifier.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PATCH /requests/{id} (the `PatchRequestsId` operationId).
	PatchRequestsIdWithResponse(ctx context.Context, id int, body PatchRequestsIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchRequestsIdResponse, error)

	// GetRequestsIdAttachmentsWithResponse Get attachments specific request
	//
	// This endpoint retrieves the attachments of a service request by its identifier.  This does not include attachments to notes.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /requests/{id}/attachments (the `GetRequestsIdAttachments` operationId).
	GetRequestsIdAttachmentsWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*GetRequestsIdAttachmentsResponse, error)

	// PatchTasksIdWithBodyWithResponse Update a specific task
	//
	// This endpoint allows partial updates to a task by its identifier.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PATCH /tasks/{id} (the `PatchTasksId` operationId).
	PatchTasksIdWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchTasksIdResponse, error)

	// PatchTasksIdWithResponse Update a specific task
	//
	// This endpoint allows partial updates to a task by its identifier.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PATCH /tasks/{id} (the `PatchTasksId` operationId).
	PatchTasksIdWithResponse(ctx context.Context, id int, body PatchTasksIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchTasksIdResponse, error)
}

type GetHeartbeatResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r GetHeartbeatResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetHeartbeatResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHeartbeatResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHeartbeatResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostRequestsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *RequestResponseSchema
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PostRequestsResponse) GetJSON200() *RequestResponseSchema {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r PostRequestsResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r PostRequestsResponse) GetJSON500() *Error {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r PostRequestsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostRequestsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostRequestsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostRequestsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetRequestsIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *RequestResponseSchema
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetRequestsIdResponse) GetJSON200() *RequestResponseSchema {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r GetRequestsIdResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetRequestsIdResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r GetRequestsIdResponse) GetJSON500() *Error {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r GetRequestsIdResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetRequestsIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRequestsIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetRequestsIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PatchRequestsIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *RequestResponseSchema
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PatchRequestsIdResponse) GetJSON200() *RequestResponseSchema {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r PatchRequestsIdResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r PatchRequestsIdResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r PatchRequestsIdResponse) GetJSON500() *Error {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r PatchRequestsIdResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PatchRequestsIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PatchRequestsIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PatchRequestsIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetRequestsIdAttachmentsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *AttachmentResponseSchema
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetRequestsIdAttachmentsResponse) GetJSON200() *AttachmentResponseSchema {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r GetRequestsIdAttachmentsResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetRequestsIdAttachmentsResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r GetRequestsIdAttachmentsResponse) GetJSON500() *Error {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r GetRequestsIdAttachmentsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetRequestsIdAttachmentsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRequestsIdAttachmentsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetRequestsIdAttachmentsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PatchTasksIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *TaskResponseSchema
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PatchTasksIdResponse) GetJSON200() *TaskResponseSchema {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r PatchTasksIdResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r PatchTasksIdResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r PatchTasksIdResponse) GetJSON500() *Error {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r PatchTasksIdResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PatchTasksIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PatchTasksIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PatchTasksIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetHeartbeatWithResponse Ping the API
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /heartbeat (the `GetHeartbeat` operationId).
func (c *ClientWithResponses) GetHeartbeatWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHeartbeatResponse, error) {
	rsp, err := c.GetHeartbeat(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHeartbeatResponse(rsp)
}

// PostRequestsWithBodyWithResponse Create a new enterprise service request
//
// This endpoint allows you to create a new enterprise service request.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /requests (the `PostRequests` operationId).
func (c *ClientWithResponses) PostRequestsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostRequestsResponse, error) {
	rsp, err := c.PostRequestsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostRequestsResponse(rsp)
}

// PostRequestsWithResponse Create a new enterprise service request
//
// This endpoint allows you to create a new enterprise service request.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /requests (the `PostRequests` operationId).
func (c *ClientWithResponses) PostRequestsWithResponse(ctx context.Context, body PostRequestsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostRequestsResponse, error) {
	rsp, err := c.PostRequests(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostRequestsResponse(rsp)
}

// GetRequestsIdWithResponse Get details of a specific request
//
// This endpoint retrieves the details of a service request by its identifier.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /requests/{id} (the `GetRequestsId` operationId).
func (c *ClientWithResponses) GetRequestsIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*GetRequestsIdResponse, error) {
	rsp, err := c.GetRequestsId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRequestsIdResponse(rsp)
}

// PatchRequestsIdWithBodyWithResponse Update a specific request
//
// This endpoint allows partial updates to a service request by its identifier.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PATCH /requests/{id} (the `PatchRequestsId` operationId).
func (c *ClientWithResponses) PatchRequestsIdWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchRequestsIdResponse, error) {
	rsp, err := c.PatchRequestsIdWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchRequestsIdResponse(rsp)
}

// PatchRequestsIdWithResponse Update a specific request
//
// This endpoint allows partial updates to a service request by its identifier.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PATCH /requests/{id} (the `PatchRequestsId` operationId).
func (c *ClientWithResponses) PatchRequestsIdWithResponse(ctx context.Context, id int, body PatchRequestsIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchRequestsIdResponse, error) {
	rsp, err := c.PatchRequestsId(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchRequestsIdResponse(rsp)
}

// GetRequestsIdAttachmentsWithResponse Get attachments specific request
//
// This endpoint retrieves the attachments of a service request by its identifier.  This does not include attachments to notes.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /requests/{id}/attachments (the `GetRequestsIdAttachments` operationId).
func (c *ClientWithResponses) GetRequestsIdAttachmentsWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*GetRequestsIdAttachmentsResponse, error) {
	rsp, err := c.GetRequestsIdAttachments(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRequestsIdAttachmentsResponse(rsp)
}

// PatchTasksIdWithBodyWithResponse Update a specific task
//
// This endpoint allows partial updates to a task by its identifier.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PATCH /tasks/{id} (the `PatchTasksId` operationId).
func (c *ClientWithResponses) PatchTasksIdWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchTasksIdResponse, error) {
	rsp, err := c.PatchTasksIdWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchTasksIdResponse(rsp)
}

// PatchTasksIdWithResponse Update a specific task
//
// This endpoint allows partial updates to a task by its identifier.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PATCH /tasks/{id} (the `PatchTasksId` operationId).
func (c *ClientWithResponses) PatchTasksIdWithResponse(ctx context.Context, id int, body PatchTasksIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchTasksIdResponse, error) {
	rsp, err := c.PatchTasksId(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchTasksIdResponse(rsp)
}

// ParseGetHeartbeatResponse parses an HTTP response from a GetHeartbeatWithResponse call
func ParseGetHeartbeatResponse(rsp *http.Response) (*GetHeartbeatResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHeartbeatResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePostRequestsResponse parses an HTTP response from a PostRequestsWithResponse call
func ParsePostRequestsResponse(rsp *http.Response) (*PostRequestsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostRequestsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RequestResponseSchema
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetRequestsIdResponse parses an HTTP response from a GetRequestsIdWithResponse call
func ParseGetRequestsIdResponse(rsp *http.Response) (*GetRequestsIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRequestsIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RequestResponseSchema
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePatchRequestsIdResponse parses an HTTP response from a PatchRequestsIdWithResponse call
func ParsePatchRequestsIdResponse(rsp *http.Response) (*PatchRequestsIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PatchRequestsIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RequestResponseSchema
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetRequestsIdAttachmentsResponse parses an HTTP response from a GetRequestsIdAttachmentsWithResponse call
func ParseGetRequestsIdAttachmentsResponse(rsp *http.Response) (*GetRequestsIdAttachmentsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRequestsIdAttachmentsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AttachmentResponseSchema
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePatchTasksIdResponse parses an HTTP response from a PatchTasksIdWithResponse call
func ParsePatchTasksIdResponse(rsp *http.Response) (*PatchTasksIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PatchTasksIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TaskResponseSchema
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
