// Package myservices provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package myservices

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for Channel.
const (
	Chat  Channel = "Chat"
	Email Channel = "Email"
	Voice Channel = "Voice"
)

// Valid indicates whether the value is a known member of the Channel enum.
func (e Channel) Valid() bool {
	switch e {
	case Chat:
		return true
	case Email:
		return true
	case Voice:
		return true
	default:
		return false
	}
}

// Defines values for Source.
const (
	ContactCentre Source = "Contact Centre"
	InsideUCL     Source = "InsideUCL"
	MyHR          Source = "MyHR"
	Norman        Source = "Norman"
)

// Valid indicates whether the value is a known member of the Source enum.
func (e Source) Valid() bool {
	switch e {
	case ContactCentre:
		return true
	case InsideUCL:
		return true
	case MyHR:
		return true
	case Norman:
		return true
	default:
		return false
	}
}

// AttachmentResponseSchema defines model for attachmentResponseSchema.
type AttachmentResponseSchema struct {
	// Response Response object containing request details.
	Response *struct {
		// Request Details of the created request.
		Request *struct {
			// Attachments List of attachments for the request.  The key name for each attachment is the attachment id as will appear in custom fields of attachment type.
			Attachments *map[string]struct {
				// Filename filename of attachment
				Filename *string `json:"filename,omitempty"`

				// Id Internal id of the attachment record
				Id *int `json:"id,omitempty"`

				// Url A temporary url that can be used to download the attachment content.  This be valid for no more than 1 hour.  TODO: check this.
				Url *string `json:"url,omitempty"`
			} `json:"attachments,omitempty"`

			// Identifier Unique identifier for the request.
			Identifier *int `json:"identifier,omitempty"`
		} `json:"request,omitempty"`
	} `json:"response,omitempty"`
}

// Channel Medium of interaction to create a Request
type Channel string

// Error defines model for error.
type Error struct {
	// Code Error code.
	Code *string `json:"code,omitempty"`

	// Message Error message.
	Message *string `json:"message,omitempty"`

	// Timestamp Timestamp of the error.
	Timestamp *string `json:"timestamp,omitempty"`
}

// RequestBodySchema Details of the service request.
type RequestBodySchema struct {
	// Channel Medium of interaction to create a Request
	Channel *Channel `json:"channel,omitempty"`

	// CustomFields Custom fields specific to the request. This can contain any fields
	CustomFields *map[string]interface{} `json:"custom_fields,omitempty"`

	// RequestedByEmail Email address of person making the request. Used to lookup a person record in MyServices. Can be used as alternative to requested_by_upi.  If a ucl address, the form of userid@ucl.ac.uk is recommended over alias.
	RequestedByEmail *string `json:"requested_by_email,omitempty"`

	// RequestedByUpi UPI of person making the request. Used to lookup a person record in MyServices. If blank defaults to a system account.  requested_by_upi takes precedence over requested_by_email.
	RequestedByUpi *string `json:"requested_by_upi,omitempty"`

	// RequestedForEmail Email address of person the request is for. If blank defaults to requested_by_email. Can be used as alternative to requested_for_upi.  If a ucl address, the form of userid@ucl.ac.uk is recommended over alias.
	RequestedForEmail *string `json:"requested_for_email,omitempty"`

	// RequestedForUpi UPI of person the request is for. If blank defaults to requested_by_upi.  requested_for_upi takes precedence over requested_for_email.
	RequestedForUpi *string `json:"requested_for_upi,omitempty"`

	// ServiceInstance Service instance associated with the request.
	ServiceInstance *string `json:"service_instance,omitempty"`

	// Source Source of the request, this will be the name of a UCL service where appropriate
	Source *Source `json:"source,omitempty"`

	// SourceId A unique id for this request in the source system
	SourceId *string `json:"source_id,omitempty"`

	// Subject Subject of the request.
	Subject *string `json:"subject,omitempty"`

	// SupportDomain Domain where the request is created.
	SupportDomain string `json:"support_domain"`

	// TemplateName Name of the template used for the request.
	TemplateName string `json:"template_name"`
}

// RequestResponseSchema defines model for requestResponseSchema.
type RequestResponseSchema struct {
	// Response Response object containing request details.
	Response *struct {
		// Request Details of the created request.
		Request *struct {
			// Channel Medium of interaction to create a Request
			Channel *Channel `json:"channel,omitempty"`

			// CompletionReason Reason for request completion.
			CompletionReason *string `json:"completion_reason,omitempty"`

			// CreatedAt Timestamp when the request was created.
			CreatedAt *time.Time `json:"created_at,omitempty"`

			// CustomFields Custom fields associated with the request.
			CustomFields *map[string]interface{} `json:"custom_fields,omitempty"`

			// Identifier Unique identifier for the request.
			Identifier *int `json:"identifier,omitempty"`

			// Source Source of the request, this will be the name of a UCL service where appropriate
			Source *Source `json:"source,omitempty"`

			// SourceId A unique id for this request in the source system
			SourceId *string `json:"source_id,omitempty"`

			// Status Status of the request.
			Status *string `json:"status,omitempty"`

			// Subject Subject of the request.
			Subject *string `json:"subject,omitempty"`

			// Team Team responsible for handling the request.
			Team *string `json:"team,omitempty"`

			// Template Template used for the request.
			Template *string `json:"template,omitempty"`

			// UpdatedAt Timestamp when the request was last updated.
			UpdatedAt *time.Time `json:"updated_at,omitempty"`
		} `json:"request,omitempty"`
	} `json:"response,omitempty"`
}

// Source Source of the request, this will be the name of a UCL service where appropriate
type Source string

// TaskResponseSchema defines model for taskResponseSchema.
type TaskResponseSchema struct {
	// Response Response object containing task details.
	Response *struct {
		// Request Details of the created task.
		Request *struct {
			// CustomFields Custom fields associated with the task.
			CustomFields *map[string]interface{} `json:"custom_fields,omitempty"`

			// Identifier Unique identifier for the task.
			Identifier *int `json:"identifier,omitempty"`

			// Status Status of the task.
			Status *string `json:"status,omitempty"`
		} `json:"request,omitempty"`
	} `json:"response,omitempty"`
}

// PatchRequestsIdJSONBody defines parameters for PatchRequestsId.
type PatchRequestsIdJSONBody struct {
	// CompletionReason Reason for the completion of the request.
	CompletionReason *string `json:"completion_reason,omitempty"`

	// Status The new status of the request.
	Status *string `json:"status,omitempty"`
}

// PatchTasksIdJSONBody defines parameters for PatchTasksId.
type PatchTasksIdJSONBody struct {
	// CustomFields custom fields to add to the task
	CustomFields *map[string]interface{} `json:"custom_fields,omitempty"`

	// Note A note to add to the task.
	Note *string `json:"note,omitempty"`

	// Status The new status of the request.
	Status *string `json:"status,omitempty"`
}

// PostRequestsJSONRequestBody defines body for PostRequests for application/json ContentType.
type PostRequestsJSONRequestBody = RequestBodySchema

// PatchRequestsIdJSONRequestBody defines body for PatchRequestsId for application/json ContentType.
type PatchRequestsIdJSONRequestBody PatchRequestsIdJSONBody

// PatchTasksIdJSONRequestBody defines body for PatchTasksId for application/json ContentType.
type PatchTasksIdJSONRequestBody PatchTasksIdJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostRequestsWithBody request with any body
	PostRequestsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostRequests(ctx context.Context, body PostRequestsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetRequestsId request
	GetRequestsId(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchRequestsIdWithBody request with any body
	PatchRequestsIdWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PatchRequestsId(ctx context.Context, id int, body PatchRequestsIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetRequestsIdAttachments request
	GetRequestsIdAttachments(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchTasksIdWithBody request with any body
	PatchTasksIdWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PatchTasksId(ctx context.Context, id int, body PatchTasksIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostRequestsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostRequestsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostRequests(ctx context.Context, body PostRequestsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostRequestsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetRequestsId(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRequestsIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchRequestsIdWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchRequestsIdRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchRequestsId(ctx context.Context, id int, body PatchRequestsIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchRequestsIdRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetRequestsIdAttachments(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRequestsIdAttachmentsRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchTasksIdWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchTasksIdRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchTasksId(ctx context.Context, id int, body PatchTasksIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchTasksIdRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostRequestsRequest calls the generic PostRequests builder with application/json body
func NewPostRequestsRequest(server string, body PostRequestsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostRequestsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostRequestsRequestWithBody generates requests for PostRequests with any type of body
func NewPostRequestsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/requests")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetRequestsIdRequest generates requests for GetRequestsId
func NewGetRequestsIdRequest(server string, id int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/requests/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPatchRequestsIdRequest calls the generic PatchRequestsId builder with application/json body
func NewPatchRequestsIdRequest(server string, id int, body PatchRequestsIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchRequestsIdRequestWithBody(server, id, "application/json", bodyReader)
}

// NewPatchRequestsIdRequestWithBody generates requests for PatchRequestsId with any type of body
func NewPatchRequestsIdRequestWithBody(server string, id int, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/requests/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPatch, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetRequestsIdAttachmentsRequest generates requests for GetRequestsIdAttachments
func NewGetRequestsIdAttachmentsRequest(server string, id int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/requests/%s/attachments", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPatchTasksIdRequest calls the generic PatchTasksId builder with application/json body
func NewPatchTasksIdRequest(server string, id int, body PatchTasksIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchTasksIdRequestWithBody(server, id, "application/json", bodyReader)
}

// NewPatchTasksIdRequestWithBody generates requests for PatchTasksId with any type of body
func NewPatchTasksIdRequestWithBody(server string, id int, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tasks/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPatch, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostRequestsWithBodyWithResponse request with any body
	PostRequestsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostRequestsResponse, error)

	PostRequestsWithResponse(ctx context.Context, body PostRequestsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostRequestsResponse, error)

	// GetRequestsIdWithResponse request
	GetRequestsIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*GetRequestsIdResponse, error)

	// PatchRequestsIdWithBodyWithResponse request with any body
	PatchRequestsIdWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchRequestsIdResponse, error)

	PatchRequestsIdWithResponse(ctx context.Context, id int, body PatchRequestsIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchRequestsIdResponse, error)

	// GetRequestsIdAttachmentsWithResponse request
	GetRequestsIdAttachmentsWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*GetRequestsIdAttachmentsResponse, error)

	// PatchTasksIdWithBodyWithResponse request with any body
	PatchTasksIdWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchTasksIdResponse, error)

	PatchTasksIdWithResponse(ctx context.Context, id int, body PatchTasksIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchTasksIdResponse, error)
}

type PostRequestsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RequestResponseSchema
	JSON400      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r PostRequestsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostRequestsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostRequestsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetRequestsIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RequestResponseSchema
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetRequestsIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRequestsIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetRequestsIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PatchRequestsIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RequestResponseSchema
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r PatchRequestsIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PatchRequestsIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PatchRequestsIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetRequestsIdAttachmentsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AttachmentResponseSchema
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetRequestsIdAttachmentsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRequestsIdAttachmentsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetRequestsIdAttachmentsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PatchTasksIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TaskResponseSchema
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r PatchTasksIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PatchTasksIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PatchTasksIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// PostRequestsWithBodyWithResponse request with arbitrary body returning *PostRequestsResponse
func (c *ClientWithResponses) PostRequestsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostRequestsResponse, error) {
	rsp, err := c.PostRequestsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostRequestsResponse(rsp)
}

func (c *ClientWithResponses) PostRequestsWithResponse(ctx context.Context, body PostRequestsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostRequestsResponse, error) {
	rsp, err := c.PostRequests(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostRequestsResponse(rsp)
}

// GetRequestsIdWithResponse request returning *GetRequestsIdResponse
func (c *ClientWithResponses) GetRequestsIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*GetRequestsIdResponse, error) {
	rsp, err := c.GetRequestsId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRequestsIdResponse(rsp)
}

// PatchRequestsIdWithBodyWithResponse request with arbitrary body returning *PatchRequestsIdResponse
func (c *ClientWithResponses) PatchRequestsIdWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchRequestsIdResponse, error) {
	rsp, err := c.PatchRequestsIdWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchRequestsIdResponse(rsp)
}

func (c *ClientWithResponses) PatchRequestsIdWithResponse(ctx context.Context, id int, body PatchRequestsIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchRequestsIdResponse, error) {
	rsp, err := c.PatchRequestsId(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchRequestsIdResponse(rsp)
}

// GetRequestsIdAttachmentsWithResponse request returning *GetRequestsIdAttachmentsResponse
func (c *ClientWithResponses) GetRequestsIdAttachmentsWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*GetRequestsIdAttachmentsResponse, error) {
	rsp, err := c.GetRequestsIdAttachments(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRequestsIdAttachmentsResponse(rsp)
}

// PatchTasksIdWithBodyWithResponse request with arbitrary body returning *PatchTasksIdResponse
func (c *ClientWithResponses) PatchTasksIdWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchTasksIdResponse, error) {
	rsp, err := c.PatchTasksIdWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchTasksIdResponse(rsp)
}

func (c *ClientWithResponses) PatchTasksIdWithResponse(ctx context.Context, id int, body PatchTasksIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchTasksIdResponse, error) {
	rsp, err := c.PatchTasksId(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchTasksIdResponse(rsp)
}

// ParsePostRequestsResponse parses an HTTP response from a PostRequestsWithResponse call
func ParsePostRequestsResponse(rsp *http.Response) (*PostRequestsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostRequestsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RequestResponseSchema
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetRequestsIdResponse parses an HTTP response from a GetRequestsIdWithResponse call
func ParseGetRequestsIdResponse(rsp *http.Response) (*GetRequestsIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRequestsIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RequestResponseSchema
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePatchRequestsIdResponse parses an HTTP response from a PatchRequestsIdWithResponse call
func ParsePatchRequestsIdResponse(rsp *http.Response) (*PatchRequestsIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PatchRequestsIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RequestResponseSchema
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetRequestsIdAttachmentsResponse parses an HTTP response from a GetRequestsIdAttachmentsWithResponse call
func ParseGetRequestsIdAttachmentsResponse(rsp *http.Response) (*GetRequestsIdAttachmentsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRequestsIdAttachmentsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AttachmentResponseSchema
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePatchTasksIdResponse parses an HTTP response from a PatchTasksIdWithResponse call
func ParsePatchTasksIdResponse(rsp *http.Response) (*PatchTasksIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PatchTasksIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TaskResponseSchema
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
