openapi: "3.0.0"
info:
  version: 0.0.0
  title: portal-dsh
  description: UCL ARC portal DSH API
servers:
  - url: /dsh/api/v0

paths:
  /ping:
    get:
      summary: Ping to check connectivity and auth
      security:
        - JWT: ["dsh:r"]
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ping"
        "401":
          description: Unauthorized
        "406":
          description: Not acceptable
        "503":
          description: Server error
        default:
          description: Unexpected error

  /approved-studies:
    get:
      summary: Get all approved studies
      security:
        - JWT: ["dsh:r"]
      responses:
        "200":
          description: OK
          content:
            text/csv:
              schema:
                type: string
              example: |
                caseref,study_owner_username,study_admin_usernames
                10000,ccxyz@ucl.ac.uk,admin@ucl.ac.uk
        "401":
          description: Unauthorized
        "406":
          description: Not acceptable
        "503":
          description: Server error
        default:
          description: Unexpected error

  /approved-researchers:
    get:
      summary: Get all approved researchers
      security:
        - JWT: ["dsh:r"]
      responses:
        "200":
          description: OK
          content:
            text/csv:
              schema:
                type: string
              example: |
                username,agreed_at,training_expires
                ccxyz@ucl.ac.uk,2026-02-04,2027-02-06
        "401":
          description: Unauthorized
        "406":
          description: Not acceptable
        "503":
          description: Server error
        default:
          description: Unexpected error

  /import/share-members:
    post:
      summary: Import
      security:
        - JWT: ["dsh:w"]
      description: |
        Upload a CSV file with fields, overwriting the current data
        "ShareName": Name of the 'share' == project
        "Owner": DSH username of the share owner
        "CaseRef": Caseref study identifier
        "Member": DSH username of the user associated to the project
        "MemEmailAddress": Email address of the user, linkable to the IdP for internal and external users
        "MemAccountEnabled":
        "MemAccountCreated": Date in DD/MM/YYYY format
        "MemAllDisabled":
        "MemOutboundRights":
      requestBody:
        required: true
        content:
          text/csv:
            schema:
              type: string
              format: binary
      responses:
        "204":
          description: OK
        "403":
          description: Forbidden
        "406":
          description: Study/user not found
        "500":
          description: Internal server error
        default:
          description: Unexpected error

components:
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Ping:
      type: object
      required:
        - message
      properties:
        message:
          type: string
