openapi: "3.0.0"
info:
  version: 0.0.0
  title: portal-dsh
  description: UCL ARC portal DSH API
servers:
  - url: /dsh/api/v0

paths:
  /ping:
    get:
      summary: Ping to check connectivity and auth
      security:
        - JWT: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ping"
        "401":
          description: Unauthorized
        "503":
          description: Server error
        default:
          description: Unexpected error
  /approved-researchers:
    get:
      summary: Get all approved researchers
      security:
        - JWT: [r]
      responses:
        "200":
          description: OK
          text/csv:
            schema:
              type: string
            example: |
              username,agreed_at,training_expires
              ccxyz@ucl.ac.uk,2026-02-04,2027-02-06
        "401":
          description: Unauthorized
        "503":
          description: Server error
        default:
          description: Unexpected error

components:
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Ping:
      type: object
      required:
        - message
      properties:
        message:
          type: string
