openapi: "3.0.0"
info:
  version: 0.0.0
  title: portal-tre
  description: UCL ARC portal TRE API
servers:
  - url: /tre/api/v0

paths:
  /user-status:
    parameters:
      - in: query
        name: username
        required: true
        schema:
          type: string
        description: Username of the user to get the status of. e.g. ccxyz@ucl.ac.uk
    get:
      description: Get the status of a user
      security:
        - JWT: ["tre:r"]
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserStatus"
        "401":
          description: Unauthenticated
        "404":
          description: Not found
        "500":
          description: Internal server error
        default:
          description: Unexpected error
  /projects/{projectName}/status:
    parameters:
      - in: path
        name: projectName
        description: TRE project name which is unique
        required: true
        schema:
          type: string
    post:
      description: Update the status of a TRE project
      security:
        - JWT: ["tre:w"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProjectStatusUpdate"
      responses:
        "204":
          description: Successfully updated status
        "401":
          description: Unauthenticated
        "404":
          description: Not found
        "406":
          description: Invalid request
        "500":
          description: Internal server error
        default:
          description: Unexpected error

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: HTTP Basic authentication
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UserStatus:
      type: object
      required:
        - is_approved_researcher
      properties:
        is_approved_researcher:
          type: boolean
          description: Is the user an approved researcher?
        nhsd_training_expires_at:
          type: string
          description: Instant at which the user's training expires in RFC3339 format

    ProjectStatusUpdate:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          description: Current status of the project in the TRE
          enum:
            - deployed
            - deleted

security:
  - basicAuth: []
