openapi: "3.0.0"
info:
  version: 0.0.0
  title: portal-tre
  description: UCL ARC portal TRE API
servers:
  - url: /tre/api/v0

paths:
  /ping:
    get:
      summary: Ping to check connectivity and auth
      security:
        - JWT: ["tre:r"]
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ping"
        "401":
          description: Unauthorized
        "406":
          $ref: "#/components/responses/InvalidObject"
        "503":
          description: Server error
        default:
          description: Unexpected error
  /user-status:
    parameters:
      - in: query
        name: username
        required: true
        schema:
          type: string
        description: Username of the user to get the status of. e.g. ccxyz@ucl.ac.uk
    get:
      description: Get the status of a user
      security:
        - JWT: ["tre:r"]
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserStatus"
        "401":
          description: Unauthenticated
        "404":
          description: Not found
        "500":
          description: Internal server error
        default:
          description: Unexpected error
  /vm-images:
    post:
      description: Create a VM image which can be used in a project
      security:
        - JWT: ["tre:w"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VMImage"
      responses:
        "204":
          description: Successfully added
        "401":
          description: Unauthenticated
        "406":
          $ref: "#/components/responses/InvalidObject"
  /projects:
    get:
      description: Get the list of TRE projects
      responses:
        "200":
          description: List of TRE projects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Project"
        "401":
          description: Unauthenticated
        "500":
          description: Internal server error
        default:
          description: Unexpected error
  /projects/{projectName}:
    parameters:
      - in: path
        name: projectName
        description: Unique TRE project name
        required: true
        schema:
          type: string
    post:
      description: Update the status of a TRE project
      security:
        - JWT: ["tre:w"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProjectUpdate"
      responses:
        "204":
          description: Successfully updated status
        "401":
          description: Unauthenticated
        "404":
          description: Not found
        "406":
          $ref: "#/components/responses/InvalidObject"
        "500":
          description: Internal server error
        default:
          description: Unexpected error

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: HTTP Basic authentication
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Ping:
      type: object
      required:
        - message
      properties:
        message:
          type: string

    UserStatus:
      type: object
      required:
        - is_approved_researcher
      properties:
        is_approved_researcher:
          type: boolean
          description: Is the user an approved researcher?
        nhsd_training_expires_at:
          type: string
          description: Instant at which the user's training expires in RFC3339 format

    VMImage:
      type: object
      required:
        - name
        - description
        - id
        - platform
      properties:
        name:
          type: string
        description:
          type: string
        id:
          type: string
          description: e.g. AMI id
        platform:
          type: string
          enum:
            - aws
            - condenser

    Project:
      type: object
      required:
        - name
        - platform
        - monthlyBudget
        - backupEnabled
        - encryptionKeyEnabled
        - owners
        - apiUsers
        - usernames
        - uids
        - uploaders
        - downloaders
        - egressRequesters
        - egressCheckers
        - desktopUsers
        - egressNumberRequiredApprovals
        - airlock
        - desktop
        - efs
      properties:
        name:
          type: string
          description: Unique project name
        platform:
          type: string
          description: TRE platform on which the project is hosted
        monthlyBudget:
          type: number
          description: Monthly budget in USD
        backupEnabled:
          type: boolean
          description: Whether backup is enabled
        encryptionKeyEnabled:
          type: boolean
          description: Whether RDSS encryption is enabled
        owners:
          type: array
          items:
            type: string
            description: Email of project IAO
        apiUsers:
          type: array
          items:
            type: string
            description: Email of TRE API user
        usernames:
          type: object
          description: Mapping of emails to usernames
          additionalProperties:
            type: string
        uids:
          type: object
          description: Mapping of user emails to Linux UIDs
          additionalProperties:
            type: integer
        uploaders:
          type: array
          items:
            type: string
            description: Email of uploader
        downloaders:
          type: array
          items:
            type: string
            description: Email of downloader
        egressRequesters:
          type: array
          items:
            type: string
            description: Email of egress requester
        egressCheckers:
          type: array
          items:
            type: string
            description: Email of egress checker
        desktopUsers:
          type: array
          items:
            type: string
            description: Email of desktop user
        egressNumberRequiredApprovals:
          type: integer
          description: Number of approvals required to egress/download
        airlock:
          $ref: "#/components/schemas/Airlock"
        desktop:
          $ref: "#/components/schemas/Image"
        efs:
          $ref: "#/components/schemas/Efs"
        desktopInstanceTypes:
          type: object
          description: Mapping of user email to desktop instance type configuration
          additionalProperties:
            $ref: "#/components/schemas/DesktopInstanceType"

    Airlock:
      type: object
      required:
        - version
        - sftpEnabled
        - sshEnabled
        - httpEnabled
        - whitelist
        - internal
        - external
      properties:
        version:
          type: integer
          description: Airlock version
        sftpEnabled:
          type: boolean
          description: Where SFTP is enabled in airlock
        sshEnabled:
          type: boolean
          description: Where SSH is enabled in airlock
        httpEnabled:
          type: boolean
          description: Where HTTP is enabled in airlock
        whitelist:
          type: array
          items:
            type: string
            description: Allowed hostname to connect to airlock
        internal:
          $ref: "#/components/schemas/Image"
        external:
          $ref: "#/components/schemas/Image"

    Image:
      description:
      type: object
      required:
        - image
      properties:
        image:
          type: string
          description: VM image ID (e.g. AMI)

    Efs:
      type: object
      required:
        - shared
      properties:
        shared:
          type: object
          description: Shared EFS configuration
          required:
            - transitionToArchive
            - bursting
          properties:
            transitionToArchive:
              type: boolean
            bursting:
              type: boolean

    DesktopInstanceType:
      type: object
      required:
        - standard
        - hpc
      properties:
        homeVolumeGb:
          type: integer
          description: Size of the home volume in GB
        standard:
          type: string
          description: Standard instance type
        hpc:
          type: string
          description: HPC instance type

    ProjectUpdate:
      type: object
      required:
        - status
        - deployed_version_updated_at
      properties:
        status:
          type: string
          description: Current status of the project in the TRE
          enum:
            - deployed
            - deleted
        deployed_version_updated_at:
          type: string
          description: Value of the updated_at field that the deployed version is, in RFC3339 format

    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string

  responses:
    InvalidObject:
      description: Bad request; invalid parameters
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

security:
  - basicAuth: []
