openapi: "3.0.0"
info:
  version: 0.0.0
  title: portal-tre
  description: UCL ARC portal TRE API
servers:
  - url: /tre/api/v0

paths:
  /ping:
    get:
      summary: Ping to check connectivity and auth
      security:
        - JWT: ["tre:r"]
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ping"
        "401":
          description: Unauthorized
        "406":
          $ref: "#/components/responses/InvalidObject"
        "503":
          description: Server error
        default:
          description: Unexpected error
  /user-status:
    parameters:
      - in: query
        name: username
        required: true
        schema:
          type: string
        description: Username of the user to get the status of. e.g. ccxyz@ucl.ac.uk
    get:
      description: Get the status of a user
      security:
        - JWT: ["tre:r"]
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserStatus"
        "401":
          description: Unauthenticated
        "404":
          description: Not found
        "500":
          description: Internal server error
        default:
          description: Unexpected error
  /vm-images:
    post:
      description: Create a VM image which can be used in a project
      security:
        - JWT: ["tre:w"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VMImage"
      responses:
        "204":
          description: Successfully added
        "401":
          description: Unauthenticated
        "406":
          $ref: "#/components/responses/InvalidObject"
  /projects:
    get:
      description: Get the list of TRE projects
      security:
        - JWT: ["tre:r"]
      responses:
        "200":
          description: List of TRE projects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Project"
        "401":
          description: Unauthenticated
        "500":
          description: Internal server error
        default:
          description: Unexpected error
  /projects/{projectName}:
    parameters:
      - in: path
        name: projectName
        description: Unique TRE project name
        required: true
        schema:
          type: string
    post:
      description: Update the status of a TRE project
      security:
        - JWT: ["tre:w"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProjectUpdate"
      responses:
        "204":
          description: Successfully updated status
        "401":
          description: Unauthenticated
        "404":
          description: Not found
        "406":
          $ref: "#/components/responses/InvalidObject"
        "500":
          description: Internal server error
        default:
          description: Unexpected error

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: HTTP Basic authentication
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Ping:
      type: object
      required:
        - message
      properties:
        message:
          type: string

    UserStatus:
      type: object
      required:
        - is_approved_researcher
      properties:
        is_approved_researcher:
          type: boolean
          description: Is the user an approved researcher?
        nhsd_training_expires_at:
          type: string
          description: Instant at which the user's training expires in RFC3339 format

    VMImage:
      type: object
      required:
        - name
        - description
        - id
        - platform
      properties:
        name:
          type: string
        description:
          type: string
        id:
          type: string
          description: e.g. AMI id
        platform:
          type: string
          enum:
            - aws
            - condenser

    Project:
      type: object
      required:
        - name
        - platform
        - monthly_budget
        - encryption_key_enabled
        - owners
        - api_users
        - usernames
        - uids
        - uploaders
        - downloaders
        - egress_requesters
        - egress_checkers
        - desktop_users
        - egress_number_required_approvals
        - requested_version_updated_at
        - airlock
        - desktop_instance_types
      properties:
        name:
          type: string
          description: Unique project name
        platform:
          type: string
          description: TRE platform on which the project is hosted
        monthly_budget:
          type: number
          description: Monthly budget in USD
        encryption_key_enabled:
          type: boolean
          description: Whether RDSS encryption is enabled
        owners:
          type: array
          items:
            type: string
            description: Email of project IAO
        api_users:
          type: array
          items:
            type: string
            description: Email of TRE API user
        usernames:
          type: object
          description: Mapping of emails to userids
          additionalProperties:
            type: string
        uids:
          type: object
          description: Mapping of user emails to Linux UIDs
          additionalProperties:
            type: integer
        uploaders:
          type: array
          items:
            type: string
            description: Email of uploader
        downloaders:
          type: array
          items:
            type: string
            description: Email of downloader
        egress_requesters:
          type: array
          items:
            type: string
            description: Email of egress requester
        egress_checkers:
          type: array
          items:
            type: string
            description: Email of egress checker
        desktop_users:
          type: array
          items:
            type: string
            description: Email of desktop user
        egress_number_required_approvals:
          type: integer
          description: Number of approvals required to egress/download
        requested_version_updated_at:
          type: string
          description: Value of the updated_at field of requested version, in RFC3339 format
        airlock:
          $ref: "#/components/schemas/Airlock"
        desktop_instance_types:
          type: object
          description: Mapping of user email to desktop instance type configuration
          additionalProperties:
            $ref: "#/components/schemas/DesktopInstanceType"

    Airlock:
      type: object
      required:
        - sftp_enabled
        - ssh_enabled
        - http_enabled
        - whitelist
      properties:
        sftp_enabled:
          type: boolean
          description: Whether SFTP is enabled in airlock
        ssh_enabled:
          type: boolean
          description: Whether SSH is enabled in airlock
        http_enabled:
          type: boolean
          description: Whether HTTP is enabled in airlock
        whitelist:
          type: array
          items:
            type: string
            description: Allowed hostname to connect to airlock

    DesktopInstanceType:
      type: object
      required:
        - image
        - standard
        - hpc
      properties:
        image:
          type: string
          description: Image to use for the desktop instance
        standard:
          type: string
          description: Standard instance type
        hpc:
          type: string
          description: HPC instance type
        home_volume_gb:
          type: integer
          description: Size of the home volume in GB

    ProjectUpdate:
      type: object
      required:
        - status
        - deployed_version_updated_at
      properties:
        status:
          type: string
          description: Current status of the project in the TRE
          enum:
            - deployed
            - deleted
        deployed_version_updated_at:
          type: string
          description: Value of the updated_at field that the deployed version is, in RFC3339 format

    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string

  responses:
    InvalidObject:
      description: Bad request; invalid parameters
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

security:
  - basicAuth: []
