---
name: Lint

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # version 7.0.0
        with:
          persist-credentials: false

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # version 6.3.0, See: https://github.com/actions/setup-python/releases
        with:
          python-version: "3.14"

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # version 6.5.0, See: https://github.com/actions/setup-go/releases
        with:
          go-version: "1.26"

      - name: Install go dependencies
        run: go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # version 6.4.0, See: https://github.com/actions/setup-node/releases
        with:
          node-version: "26"

      - name: Install node dependencies
        working-directory: web
        run: npm ci

      - name: Run pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # version 3.0.1, See: https://github.com/pre-commit/action/releases
        with:
          extra_args: --all-files
