---
name: Security

on:
  pull_request:
    paths:
      - "**.go"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gosec:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      GO111MODULE: on

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # version 7.0.1
        with:
          persist-credentials: false

      - name: Run Gosec Security Scanner
        uses: securego/gosec@deb54465fea23d19a77f037e11e6589021f8501d # v2.29.0
        with:
          args: "-concurrency=2 ./..."
