---
name: Security

on:
  pull_request:
    paths:
      - "**.go"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gosec:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      GO111MODULE: on

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # version 7.0.0
        with:
          persist-credentials: false

      - name: Run Gosec Security Scanner
        uses: securego/gosec@9e6a9843d7a4a6e3e9a8539b02612c8a4aa3f889 # v2.27.1
        with:
          args: "./..."
